// src/pages/Savings.tsx
import { InfoCircleOutlined, QuestionCircleOutlined, WarningOutlined } from '@ant-design/icons'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import BigNumber from 'bignumber.js'
import { ethers, formatUnits, parseUnits } from 'ethers'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { AnimatedNumber } from '@/components/common/AnimatedNumber'
import { FormattedInput } from '@/components/common/FormattedInput'
import { InfoCards } from '@/components/common/InfoCards'
import { PullToRefresh } from '@/components/common/PullToRefresh'
import { QuickAmounts } from '@/components/common/QuickAmounts'
import { TokenIcon } from '@/components/common/TokenIcon'
import { TransactionModal, type TransactionDetail, type TransactionStep } from '@/components/common/TransactionModal'
import { DEFAULT_CHAIN_ID } from '@/constants'
import { useDebouncedValue } from '@/hooks/useDebouncedValue'
import { feedback } from '@/lib/feedback'
import { PageScaffold, PageSection } from '@/pages/PageScaffold'
import { contractService } from '@/services/contracts'
import { useSavingsStore } from '@/stores/savings'
import { useWalletStore } from '@/stores/wallet'
import { calculatePercentageAmount, formatNumber, formatNumberK } from '@/utils/format'
import { resolveText } from '@/utils/i18n'

interface SavingsVaultView {
  userBalance: string
  wrmbBalance: string
  totalAssets: string
  currentNAV: string
  totalSupply: string
  totalMMFSupply: string
  dynamicAPY: string
  userAssetValue: string
  userIncrementAmount: string
  totalPendingAmount: string
  userSharePercentage: string
}

interface SavingsPreview {
  shares: string
  assets: string
  fee: string
}

const emptyPreview: SavingsPreview = {
  shares: '',
  assets: '',
  fee: '0'
}

const emptyVaultView: SavingsVaultView = {
  userBalance: '0',
  wrmbBalance: '0',
  totalAssets: '0',
  currentNAV: '1',
  totalSupply: '0',
  totalMMFSupply: '0',
  dynamicAPY: '0',
  userAssetValue: '0',
  userIncrementAmount: '0',
  totalPendingAmount: '0',
  userSharePercentage: '0'
}

export default function SavingsPage() {
  const { t } = useTranslation()
  const wallet = useWalletStore()
  const activeTab = useSavingsStore(state => state.activeTab)
  const setActiveTab = useSavingsStore(state => state.setActiveTab)
  const queryClient = useQueryClient()
  const chainId = wallet.chainId || DEFAULT_CHAIN_ID
  const [depositAmount, setDepositAmount] = useState('')
  const [withdrawAmount, setWithdrawAmount] = useState('')
  const [transactionVisible, setTransactionVisible] = useState(false)
  const [transactionTitle, setTransactionTitle] = useState('')
  const [transactionHash, setTransactionHash] = useState('')
  const [transactionError, setTransactionError] = useState('')
  const [transactionStatus, setTransactionStatus] = useState<'pending' | 'loading' | 'success' | 'error'>('pending')
  const [transactionStep, setTransactionStep] = useState(0)
  const debouncedDepositAmount = useDebouncedValue(depositAmount)
  const debouncedWithdrawAmount = useDebouncedValue(withdrawAmount)

  const transactionSteps: TransactionStep[] = useMemo(
    () => [
      { label: t('transaction.approve'), description: t('transaction.approveDescription') },
      { label: t('transaction.confirm'), description: t('transaction.confirmDescription') },
      { label: t('transaction.complete'), description: t('transaction.completeDescription') }
    ],
    [t]
  )

  const infoCards = useMemo(
    () => [
      {
        icon: <InfoCircleOutlined />,
        title: t('savings.whatIsSavings'),
        content: t('savings.savingsDescription')
      },
      {
        icon: <QuestionCircleOutlined />,
        title: t('savings.savingsFees'),
        content: t('savings.savingsFeesDescription')
      },
      {
        icon: <WarningOutlined />,
        title: t('savings.savingsRisks'),
        content: t('savings.savingsRisksDescription')
      }
    ],
    [t]
  )

  const vaultQuery = useQuery({
    queryKey: ['savings', 'vault', chainId, wallet.address],
    refetchInterval: wallet.isConnected ? 6_000 : 30_000,
    queryFn: async (): Promise<SavingsVaultView> => {
      const savingsContract = contractService.getSavingsVaultContract()
      const wrmbContract = contractService.getWRMBContract()
      if (!savingsContract) {
        return emptyVaultView
      }

      const baseCalls = await Promise.all([
        savingsContract.totalAssets(),
        savingsContract.totalSupply(),
        savingsContract.totalMMFSupply(),
        savingsContract.getNAV_sWRMB(),
        savingsContract.lastIncreaseAmount(),
        savingsContract.currentPendingIncreaseAmount()
      ])

      const [totalAssets, totalSupply, totalMMFSupply, nav, lastIncreaseAmount, pendingAmount] = baseCalls
      const totalAssetsValue = formatUnits(totalAssets, 18)
      const totalSupplyValue = formatUnits(totalSupply, 18)
      const totalMMFSupplyValue = formatUnits(totalMMFSupply, 18)
      const navValue = formatUnits(nav, 18)
      const pendingValue = formatUnits(pendingAmount, 18)
      const apyBase = new BigNumber(formatUnits(lastIncreaseAmount, 16))
      const apy =
        totalMMFSupplyValue === '0' ? new BigNumber(0) : apyBase.dividedBy(totalMMFSupplyValue).multipliedBy(365)
      const boostedApy =
        totalSupplyValue === '0'
          ? new BigNumber(0)
          : apy.multipliedBy(totalMMFSupplyValue || '0').dividedBy(totalSupplyValue)

      if (!wallet.address || !wrmbContract) {
        return {
          ...emptyVaultView,
          currentNAV: navValue,
          dynamicAPY: boostedApy.gt(0) ? boostedApy.toString() : '0',
          totalAssets: totalAssetsValue,
          totalMMFSupply: totalMMFSupplyValue,
          totalPendingAmount: pendingValue,
          totalSupply: totalSupplyValue
        }
      }

      const [sWRMBBalance, wrmbBalance, maxWithdraw, userIncrementAmount] = await Promise.all([
        savingsContract.balanceOf(wallet.address),
        wrmbContract.balanceOf(wallet.address),
        savingsContract.maxWithdraw(wallet.address),
        savingsContract.getUserIncrementAmount(wallet.address)
      ])

      const userBalance = formatUnits(sWRMBBalance, 18)
      const userAssetValue = formatUnits(maxWithdraw, 18)
      const userSharePercentage =
        totalSupplyValue === '0'
          ? '0'
          : new BigNumber(userBalance).dividedBy(totalSupplyValue).multipliedBy(100).toFixed(4)

      return {
        currentNAV: navValue,
        dynamicAPY: boostedApy.gt(0) ? boostedApy.toString() : '0',
        totalAssets: totalAssetsValue,
        totalMMFSupply: totalMMFSupplyValue,
        totalPendingAmount: pendingValue,
        totalSupply: totalSupplyValue,
        userAssetValue,
        userBalance,
        userIncrementAmount: formatUnits(userIncrementAmount, 18),
        userSharePercentage,
        wrmbBalance: formatUnits(wrmbBalance, 18)
      }
    }
  })

  const vault = vaultQuery.data ?? emptyVaultView

  const depositPreviewQuery = useQuery({
    enabled: Number.parseFloat(debouncedDepositAmount) > 0,
    queryKey: ['savings', 'preview', 'deposit', chainId, debouncedDepositAmount],
    queryFn: async (): Promise<SavingsPreview> => {
      const savingsContract = contractService.getSavingsVaultContract()
      if (!savingsContract || !debouncedDepositAmount) {
        return emptyPreview
      }

      const shares = await savingsContract.previewDeposit(parseUnits(debouncedDepositAmount, 18))
      return {
        shares: formatUnits(shares, 18),
        assets: debouncedDepositAmount,
        fee: '0'
      }
    }
  })

  const withdrawPreviewQuery = useQuery({
    enabled: Number.parseFloat(debouncedWithdrawAmount) > 0,
    queryKey: ['savings', 'preview', 'withdraw', chainId, debouncedWithdrawAmount],
    queryFn: async (): Promise<SavingsPreview> => {
      const savingsContract = contractService.getSavingsVaultContract()
      if (!savingsContract || !debouncedWithdrawAmount) {
        return emptyPreview
      }

      const preview = await savingsContract.previewWithdrawOfFee(parseUnits(debouncedWithdrawAmount, 18))
      return {
        shares: formatUnits(preview[0], 18),
        assets: formatUnits(preview[1], 18),
        fee: formatUnits(preview[2], 18)
      }
    }
  })

  const depositPreview = depositPreviewQuery.data ?? emptyPreview
  const withdrawPreview = withdrawPreviewQuery.data ?? emptyPreview
  const withdrawPreviewFee = useMemo(
    () => new BigNumber(withdrawAmount || '0').multipliedBy(withdrawPreview.fee || '0').toString(),
    [withdrawAmount, withdrawPreview.fee]
  )

  const isDepositValid =
    Number.parseFloat(depositAmount) > 0 && Number.parseFloat(depositAmount) <= Number.parseFloat(vault.wrmbBalance)
  const isWithdrawValid =
    Number.parseFloat(withdrawAmount) > 0 &&
    Number.parseFloat(withdrawAmount) <= Number.parseFloat(vault.userAssetValue)

  const transactionDetails = useMemo<TransactionDetail[]>(() => {
    if (activeTab === 'deposit' && depositAmount) {
      return [
        {
          label: t('pay'),
          values: [`-${formatNumber(depositAmount, 6)} WRMB`],
          highlight: true,
          type: 'debit'
        },
        {
          label: t('receive'),
          values: [`+${formatNumber(depositPreview.shares || '0', 6)} sWRMB`],
          type: 'credit'
        }
      ]
    }

    if (activeTab === 'withdraw' && withdrawAmount) {
      return [
        {
          label: t('pay'),
          values: [`-${formatNumber(withdrawPreview.shares || '0', 6)} sWRMB`],
          type: 'debit'
        },
        {
          label: t('receive'),
          values: [`+${formatNumber(withdrawPreview.assets || '0', 6)} WRMB`],
          highlight: true,
          type: 'credit'
        }
      ]
    }

    return []
  }, [
    activeTab,
    depositAmount,
    depositPreview.shares,
    t,
    withdrawAmount,
    withdrawPreview.assets,
    withdrawPreview.shares
  ])

  const refreshData = async () => {
    await queryClient.invalidateQueries({ queryKey: ['savings'] })
  }

  const resetTransactionState = () => {
    setTransactionHash('')
    setTransactionError('')
    setTransactionStatus('pending')
    setTransactionStep(0)
  }

  const handleDeposit = async () => {
    if (!wallet.isConnected || !wallet.address || !isDepositValid) {
      return
    }

    const wrmbContract = contractService.getWRMBContract(true)
    const savingsContract = contractService.getSavingsVaultContract(true)
    if (!wrmbContract || !savingsContract) {
      feedback.error(t('savings.depositFailed'))
      return
    }

    setTransactionTitle(t('savings.depositTransaction'))
    setTransactionVisible(true)
    setTransactionStatus('pending')
    setTransactionStep(0)

    try {
      const amountWei = parseUnits(depositAmount, 18)
      const savingsAddress = await savingsContract.getAddress()
      const allowance = await wrmbContract.allowance(wallet.address, savingsAddress)

      if (allowance < amountWei) {
        setTransactionStatus('loading')
        const approveTx = await wrmbContract.approve(savingsAddress, ethers.MaxUint256)
        await approveTx.wait()
      }

      setTransactionStep(1)
      setTransactionStatus('loading')
      const depositTx = await savingsContract.deposit(amountWei, wallet.address)
      const receipt = await depositTx.wait()

      setTransactionStep(2)
      setTransactionStatus('success')
      setTransactionHash(receipt.hash)
      setDepositAmount('')
      await refreshData()
      feedback.success(t('savings.depositSuccess'))
    } catch (error) {
      setTransactionStatus('error')
      setTransactionError(error instanceof Error ? error.message : t('savings.depositFailed'))
    }
  }

  const handleWithdraw = async () => {
    if (!wallet.isConnected || !wallet.address || !isWithdrawValid) {
      return
    }

    const savingsContract = contractService.getSavingsVaultContract(true)
    if (!savingsContract) {
      feedback.error(t('savings.withdrawFailed'))
      return
    }

    setTransactionTitle(t('savings.withdrawTransaction'))
    setTransactionVisible(true)
    setTransactionStatus('loading')
    setTransactionStep(0)

    try {
      const amountWei = parseUnits(withdrawAmount, 18)
      const isFullWithdraw = withdrawAmount === vault.userAssetValue

      const transaction = isFullWithdraw
        ? await savingsContract.redeem(parseUnits(vault.userBalance, 18), wallet.address, wallet.address)
        : await savingsContract.withdraw(amountWei, wallet.address, wallet.address)

      setTransactionStep(1)
      const receipt = await transaction.wait()
      setTransactionStep(2)
      setTransactionStatus('success')
      setTransactionHash(receipt.hash)
      setWithdrawAmount('')
      await refreshData()
      feedback.success(t('savings.withdrawSuccess'))
    } catch (error) {
      setTransactionStatus('error')
      setTransactionError(error instanceof Error ? error.message : t('savings.withdrawFailed'))
    }
  }

  const pageTitle = resolveText(t('navigation.savings'), 'navigation.savings', 'Savings')
  const vaultOverviewTitle = resolveText(t('savings.vaultOverview'), 'savings.vaultOverview', 'Vault Overview')
  const statisticsTitle = 'Statistics'
  const connectWalletLabel = resolveText(t('wallet.connectWallet'), 'wallet.connectWallet', 'Connect Wallet')
  const depositLabel = resolveText(t('savings.deposit'), 'savings.deposit', 'Deposit')
  const withdrawLabel = resolveText(t('savings.withdraw'), 'savings.withdraw', 'Withdraw')

  return (
    <PageScaffold title={pageTitle}>
      <PullToRefresh isRefreshing={vaultQuery.isRefetching}>
        {!wallet.isConnected ? <div className="app-inline-note is-info mb-6">{connectWalletLabel}</div> : null}

        <PageSection>
          <div className="mb-6">
            <h2 className="page-section-title">{vaultOverviewTitle}</h2>
          </div>

          <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-6">
            <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="text-sm font-semibold text-[var(--text-secondary)]">
                  {resolveText(t('savings.assetValue'), 'savings.assetValue', 'Asset Value')}
                </div>
                <div className="mt-2 text-sm text-[var(--text-secondary)]">
                  {resolveText(t('savings.apy'), 'savings.apy', 'APY')} {formatNumber(vault.dynamicAPY, 2)}%
                </div>
              </div>
              <div className="rounded-full bg-[var(--card-bg)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.08em] text-[var(--text-secondary)]">
                sWRMB Vault
              </div>
            </div>

            <div className="mt-6 flex items-center gap-3 text-3xl font-bold text-[var(--number-color)]">
              <TokenIcon size="large" symbol="WRMB" />
              <AnimatedNumber decimals={4} value={vault.userAssetValue} />
            </div>
          </div>
        </PageSection>

        <PageSection>
          <div className="mb-8 flex items-center justify-center rounded-2xl bg-[var(--bg-secondary)] p-1">
            <button
              className={`w-full rounded-xl px-4 py-3 text-sm font-semibold transition ${
                activeTab === 'deposit' ? 'bg-[var(--primary-color)] text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
              type="button"
              onClick={() => {
                setActiveTab('deposit')
                setDepositAmount('')
                setWithdrawAmount('')
              }}
            >
              {depositLabel}
            </button>
            <button
              className={`w-full rounded-xl px-4 py-3 text-sm font-semibold transition ${
                activeTab === 'withdraw' ? 'bg-[var(--primary-color)] text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
              type="button"
              onClick={() => {
                setActiveTab('withdraw')
                setDepositAmount('')
                setWithdrawAmount('')
              }}
            >
              {withdrawLabel}
            </button>
          </div>

          {activeTab === 'deposit' ? (
            <div className="space-y-6">
              <div>
                <div className="mb-3 flex items-center justify-between gap-4 text-sm">
                  <span className="font-medium text-[var(--text-primary)]">{depositLabel}</span>
                  <span className="text-[var(--text-secondary)]">
                    {resolveText(t('wrap.balance'), 'wrap.balance', 'Balance')}: {formatNumberK(vault.wrmbBalance)} WRMB
                  </span>
                </div>
                <FormattedInput
                  className="w-full"
                  decimals={6}
                  maxDecimals={18}
                  modelValue={depositAmount}
                  placeholder={`${formatNumberK(vault.wrmbBalance)} ${t('available')}`}
                  size="large"
                  useAbbreviation
                  onChange={setDepositAmount}
                >
                  <span className="flex items-center gap-2">
                    <TokenIcon size="medium" symbol="WRMB" />
                    <span>WRMB</span>
                  </span>
                </FormattedInput>
                <div className="mt-4">
                  <QuickAmounts
                    maxLabel={t('common.max')}
                    onSelectMax={() => setDepositAmount(vault.wrmbBalance)}
                    onSelectPercentage={percentage => setDepositAmount(calculatePercentageAmount(vault.wrmbBalance, percentage))}
                  />
                </div>
              </div>

              {depositPreview.shares ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
                  <h3 className="text-base font-semibold text-[var(--text-primary)]">
                    {resolveText(t('savings.preview'), 'savings.preview', 'Preview')}
                  </h3>
                  <div className="mt-4 space-y-3 text-sm">
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('savings.youWillReceive'), 'savings.youWillReceive', 'You Will Receive')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(depositPreview.shares, 2)} sWRMB</span>
                    </div>
                    <div className="flex items-center justify-between gap-4 border-t border-[var(--border-color)] pt-3">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('savings.currentExchangeRate'), 'savings.currentExchangeRate', 'Current Exchange Rate')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">
                        1 WRMB to {formatNumber(1 / Number.parseFloat(vault.currentNAV || '1'), 6)} sWRMB
                      </span>
                    </div>
                  </div>
                </div>
              ) : null}

              <button
                className="app-action-button is-primary w-full"
                disabled={!isDepositValid || !wallet.isConnected}
                type="button"
                onClick={() => void handleDeposit()}
              >
                {wallet.isConnected ? depositLabel : connectWalletLabel}
              </button>
            </div>
          ) : (
            <div className="space-y-6">
              <div>
                <div className="mb-3 flex items-center justify-between gap-4 text-sm">
                  <span className="font-medium text-[var(--text-primary)]">{withdrawLabel}</span>
                  <span className="text-[var(--text-secondary)]">
                    {resolveText(t('wrap.balance'), 'wrap.balance', 'Balance')}: {formatNumberK(vault.userAssetValue)} WRMB
                  </span>
                </div>
                <FormattedInput
                  className="w-full"
                  decimals={6}
                  maxDecimals={18}
                  modelValue={withdrawAmount}
                  placeholder={`${formatNumberK(vault.userAssetValue)} ${t('available')}`}
                  size="large"
                  useAbbreviation
                  onChange={setWithdrawAmount}
                >
                  <span className="flex items-center gap-2">
                    <TokenIcon size="medium" symbol="WRMB" />
                    <span>WRMB</span>
                  </span>
                </FormattedInput>
                <div className="mt-4">
                  <QuickAmounts
                    maxLabel={t('common.max')}
                    onSelectMax={() => setWithdrawAmount(vault.userAssetValue)}
                    onSelectPercentage={percentage => setWithdrawAmount(calculatePercentageAmount(vault.userAssetValue, percentage))}
                  />
                </div>
              </div>

              {withdrawPreview.shares ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
                  <h3 className="text-base font-semibold text-[var(--text-primary)]">
                    {resolveText(t('savings.preview'), 'savings.preview', 'Preview')}
                  </h3>
                  <div className="mt-4 space-y-3 text-sm">
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('savings.youWillReceive'), 'savings.youWillReceive', 'You Will Receive')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(withdrawPreview.assets, 2)} WRMB</span>
                    </div>
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('savings.fee'), 'savings.fee', 'Fee')} ({formatNumber(new BigNumber(withdrawPreview.fee).multipliedBy(100).toString())}%)
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(withdrawPreviewFee, 2)} WRMB</span>
                    </div>
                    <div className="flex items-center justify-between gap-4 border-t border-[var(--border-color)] pt-3">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('savings.currentExchangeRate'), 'savings.currentExchangeRate', 'Current Exchange Rate')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">1 sWRMB to {formatNumber(vault.currentNAV, 6)} WRMB</span>
                    </div>
                  </div>
                </div>
              ) : null}

              <button
                className="app-action-button is-primary w-full"
                disabled={!isWithdrawValid || !wallet.isConnected}
                type="button"
                onClick={() => void handleWithdraw()}
              >
                {wallet.isConnected ? withdrawLabel : connectWalletLabel}
              </button>
            </div>
          )}
        </PageSection>

        <PageSection>
          <div className="mb-6">
            <h2 className="page-section-title">{statisticsTitle}</h2>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-5">
              <div className="text-sm font-semibold uppercase tracking-[0.06em] text-[var(--text-secondary)]">
                {resolveText(t('savings.totalSupply'), 'savings.totalSupply', 'Total Supply')}
              </div>
              <div className="mt-3 text-2xl font-bold text-[var(--number-color)]">{formatNumberK(vault.totalAssets)}</div>
            </div>
            <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-5">
              <div className="text-sm font-semibold uppercase tracking-[0.06em] text-[var(--text-secondary)]">
                {resolveText(t('savings.yourShare'), 'savings.yourShare', 'Your Share')}
              </div>
              <div className="mt-3 text-2xl font-bold text-[var(--number-color)]">{formatNumberK(vault.userSharePercentage)}%</div>
            </div>
            <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-5">
              <div className="text-sm font-semibold uppercase tracking-[0.06em] text-[var(--text-secondary)]">
                {resolveText(t('savings.totalValue'), 'savings.totalValue', 'Total Value')}
              </div>
              <div className="mt-3 text-2xl font-bold text-[var(--number-color)]">
                ${formatNumberK(new BigNumber(vault.totalAssets).multipliedBy(0.14).toString(), 2)}
              </div>
            </div>
            <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-5">
              <div className="text-sm font-semibold uppercase tracking-[0.06em] text-[var(--text-secondary)]">
                {resolveText(t('savings.yourValue'), 'savings.yourValue', 'Your Value')}
              </div>
              <div className="mt-3 text-2xl font-bold text-[var(--number-color)]">
                ${formatNumberK(new BigNumber(vault.userAssetValue).multipliedBy(0.14).toString(), 2)}
              </div>
            </div>
          </div>
        </PageSection>

        <InfoCards cards={infoCards} />
      </PullToRefresh>

      <TransactionModal
        currentStep={transactionStep}
        errorMessage={transactionError}
        status={transactionStatus}
        steps={transactionSteps}
        title={transactionTitle}
        transactionDetails={transactionDetails}
        transactionHash={transactionHash}
        visible={transactionVisible}
        onClose={() => {
          setTransactionVisible(false)
          resetTransactionState()
        }}
        onRetry={() => {
          if (activeTab === 'deposit') {
            void handleDeposit()
          } else {
            void handleWithdraw()
          }
        }}
      />
    </PageScaffold>
  )
}

// src/views/Savings.vue
<template>
  <div class="h-full">
    <PullToRefresh :is-pulling="isPulling" :is-refreshing="isRefreshing" :pull-distance="pullDistance"
      :can-refresh="canRefresh">
      <!-- Vault Overview -->
      <div class="vault-overview">
        <h2 class="section-title">
          {{ $t('savings.vaultOverview') }}
        </h2>

        <div class="overview-grid">
          <!-- Total Assets -->
          <div class="overview-card">
            <div class="card-header">
              <h3 class="card-title">{{ $t('savings.assetValue') }}</h3>
              <div class="card-subtitle">
                {{ $t('savings.apy') }} {{ formatNumber(savingsStore.dynamicAPY) }}%
              </div>
            </div>
            <div class="card-value">
              <img src="../assets/wrmb.png" alt="" class="wrmb-icon">
              <AnimatedNumber class="animated-number" :value="savingsStore.userAssetValue"
                :auto-increment="walletStore.isConnected && parseFloat(savingsStore.userAssetValue) > 0"
                :increment-amount="parseFloat(savingsStore.userIncrementAmount)" :increment-interval="1000"
                :cache-key="`userAssetValue_${walletStore.address}`" :use-cache="false" />
            </div>
          </div>
        </div>
      </div>

      <!-- Action Tabs -->
      <div class="action-section">
        <el-tabs v-model="activeTab" class="savings-tabs">
          <!-- Deposit Tab -->
          <el-tab-pane :label="$t('savings.deposit')" name="deposit">
            <div class="tab-content">
              <div class="action-form">
                <div class="input-section">
                  <div class="input-group">
                    <FormattedInput v-model="depositAmount"
                      :placeholder="formatNumberK(savingsStore.wrmbBalance) + '  ' + $t('available')" size="large"
                      class="amount-input" :decimals="6" :use-abbreviation="true" :max-decimals="18"
                      @input-change="handleDepositAmountChange">
                      <div class="token-symbol-selected">
                        <TokenIcon symbol="WRMB" size="medium" />
                        <span class="token-symbol-text">WRMB</span>
                      </div>
                    </FormattedInput>
                  </div>

                  <!-- Quick Amount Buttons -->
                  <QuickAmounts :max-label="$t('common.max')" @select-percentage="setDepositPercentage"
                    @select-max="setMaxDeposit" />
                </div>

                <!-- Preview -->
                <div v-if="depositPreview.shares" class="preview-section">
                  <h4 class="preview-title">{{ $t('savings.preview') }}</h4>
                  <div class="preview-details">
                    <div class="preview-row">
                      <span>{{ $t('savings.youWillReceive') }}</span>
                      <span class="preview-value">{{ formatNumber(depositPreview.shares, 2) }} sWRMB</span>
                    </div>
                    <div class="preview-row exchange-rate">
                      <span>{{ $t('savings.currentExchangeRate') }}</span>
                      <span class="preview-value">1 WRMB ≈ {{ formatNumber((1 / parseFloat(savingsStore.currentNAV ||
                        '1')), 6) }}
                        sWRMB</span>
                    </div>
                  </div>
                </div>

                <el-button type="primary" size="large" :loading="savingsStore.depositInProgress"
                  :disabled="!isDepositValid" @click="handleDeposit" class="action-button">
                  {{ $t('savings.deposit') }}
                </el-button>
              </div>
            </div>
          </el-tab-pane>

          <!-- Withdraw Tab -->
          <el-tab-pane :label="$t('savings.withdraw')" name="withdraw">
            <div class="tab-content">
              <div class="action-form">
                <div class="input-section">
                  <div class="input-group">
                    <FormattedInput v-model="withdrawAmount"
                      :placeholder="formatNumberK(savingsStore.userAssetValue) + '  ' + $t('available')" size="large"
                      class="amount-input" :decimals="6" :use-abbreviation="true" :max-decimals="18"
                      @input-change="handleWithdrawAmountChange">
                      <div class="token-symbol-selected">
                        <TokenIcon symbol="WRMB" size="medium" />
                        <span class="token-symbol-text">WRMB</span>
                      </div>
                    </FormattedInput>
                  </div>

                  <!-- Quick Amount Buttons -->
                  <QuickAmounts :max-label="$t('common.max')" @select-percentage="setWithdrawPercentage"
                    @select-max="setMaxWithdraw" />
                </div>

                <!-- Preview -->
                <div v-if="withdrawPreview.shares" class="preview-section">
                  <h4 class="preview-title">{{ $t('savings.preview') }}</h4>
                  <div class="preview-details">
                    <div class="preview-row">
                      <span>{{ $t('savings.youWillReceive') }}</span>
                      <span class="preview-value">{{ formatNumber(withdrawPreview.assets, 2) }} WRMB</span>
                    </div>
                    <div class="preview-row">
                      <span>{{ $t('savings.fee') }} ({{ formatNumber((parseFloat(withdrawPreview.fee) *
                        100).toString())
                        }}%)</span>
                      <span class="fee-value">{{ formatNumber(withdrawPreviewFee, 2) }} WRMB</span>
                    </div>

                    <div class="preview-row exchange-rate">
                      <span>{{ $t('savings.currentExchangeRate') }}</span>
                      <span class="preview-value">1 sWRMB ≈ {{ formatNumber(savingsStore.currentNAV, 6) }} WRMB</span>
                    </div>
                  </div>
                </div>

                <el-button type="primary" size="large" :loading="savingsStore.withdrawInProgress"
                  :disabled="!isWithdrawValid" @click="handleWithdraw" class="action-button">
                  {{ $t('savings.withdraw') }}
                </el-button>
              </div>
            </div>
          </el-tab-pane>
        </el-tabs>
      </div>

      <!-- Statistics -->
      <div class="statistics-section">
        <div class="stats-grid">
          <div class="stat-item">
            <div class="stat-label">{{ $t('savings.totalSupply') }}</div>
            <div class="stat-value">{{ formatNumberK(savingsStore.totalAssets) }}</div>
          </div>

          <div class="stat-item">
            <div class="stat-label">{{ $t('savings.yourShare') }}</div>
            <div class="stat-value">{{ formatNumberK(savingsStore.userSharePercentage) }}%</div>
          </div>

          <div class="stat-item">
            <div class="stat-label">{{ $t('savings.totalValue') }}</div>
            <div class="stat-value">${{ formatNumberK(parseFloat(savingsStore.totalAssets) * 0.14, 2) }}</div>
          </div>

          <div class="stat-item">
            <div class="stat-label">{{ $t('savings.yourValue') }}</div>
            <div class="stat-value">${{ formatNumberK(parseFloat(savingsStore.userAssetValue) * 0.14, 2) }}</div>
          </div>
        </div>
      </div>

      <!-- Information Cards -->
      <InfoCards :cards="infoCards" />
    </PullToRefresh>

    <!-- Transaction Modal -->
    <TransactionModal v-model:visible="showTransactionModal" :title="transactionModalTitle" :steps="transactionSteps"
      :current-step="currentTransactionStep" :status="transactionStatus" :transaction-details="transactionDetails"
      :transaction-hash="transactionHash" :error-message="transactionError" @close="handleTransactionModalClose"
      @retry="handleTransactionRetry" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { parseUnits } from 'ethers'
import { InfoFilled, QuestionFilled, WarningFilled } from '@element-plus/icons-vue'

import PullToRefresh from '@/components/common/PullToRefresh.vue'
import TransactionModal from '@/components/common/TransactionModal.vue'
import AnimatedNumber from '@/components/common/AnimatedNumber.vue'
import FormattedInput from '@/components/common/FormattedInput.vue'
import QuickAmounts from '@/components/common/QuickAmounts.vue'
import InfoCards from '@/components/common/InfoCards.vue'
import { useSavingsStore } from '@/stores/savings'
import { useWalletStore } from '@/stores/wallet'
import { contractService } from '@/services/contracts'
import { formatNumber, formatNumberK, calculatePercentageAmount } from '@/utils/format'
import { debounce } from '@/utils/debounce'
import { usePullToRefresh } from '@/composables/usePullToRefresh'

const { t } = useI18n()
const savingsStore = useSavingsStore()
const walletStore = useWalletStore()

const activeTab = ref('deposit')
const depositAmount = ref('')
const withdrawAmount = ref('')
const depositPreview = ref({
  shares: '',
  fee: '0'
})
const withdrawPreview = ref({
  shares: '',
  assets: '',
  fee: '0'
})

// Info Cards data
const infoCards = computed(() => [
  {
    icon: InfoFilled,
    title: t('savings.whatIsSavings'),
    content: t('savings.savingsDescription')
  },
  {
    icon: QuestionFilled,
    title: t('savings.savingsFees'),
    content: t('savings.savingsFeesDescription')
  },
  {
    icon: WarningFilled,
    title: t('savings.savingsRisks'),
    content: t('savings.savingsRisksDescription')
  }
])

const isQuickAmountModeOfDeposit = ref(false)
const isQuickAmountModeOfWithdraw = ref(false)

// Transaction Modal
const showTransactionModal = ref(false)
const transactionModalTitle = ref('')
const currentTransactionStep = ref(0)
const transactionStatus = ref<'pending' | 'loading' | 'success' | 'error'>('pending')
const transactionHash = ref('')
const transactionError = ref('')

const transactionSteps = ref([
  { label: t('transaction.approve'), description: t('transaction.approveDescription') },
  { label: t('transaction.confirm'), description: t('transaction.confirmDescription') },
  { label: t('transaction.complete'), description: t('transaction.completeDescription') }
])

const transactionDetails = computed(() => {
  const details: {
    label: string
    values: string[]
    highlight?: boolean
    type?: 'debit' | 'credit'
  }[] = []

  if (activeTab.value === 'deposit' && depositAmount.value) {
    details.push(
      { label: t('pay'), values: [`-${formatNumber(depositAmount.value, 6)} WRMB`], highlight: true, type: 'debit' },
      { label: t('receive'), values: [`+${formatNumber(depositPreview.value?.shares || '0', 6)} sWRMB`], type: 'credit' }
    )
  } else if (activeTab.value === 'withdraw' && withdrawAmount.value) {
    details.push(
      { label: t('pay'), values: [`-${formatNumber(withdrawPreview.value?.shares || '0', 6)} sWRMB`], type: 'debit' },
      { label: t('receive'), values: [`+${formatNumber(withdrawPreview.value?.assets || '0', 6)} WRMB`], highlight: true, type: 'credit' },
    )
    // if (parseFloat(withdrawPreviewFee.value) > 0) {
    //   details.push({ label: t('savings.fee'), value: `-${formatNumber(withdrawPreviewFee.value, 6)} WRMB`, type: 'debit' })
    // }
  }

  return details
})

const isDepositValid = computed(() => {
  const amount = parseFloat(depositAmount.value)
  return amount > 0 && amount <= parseFloat(savingsStore.wrmbBalance)
})

const isWithdrawValid = computed(() => {
  const amount = parseFloat(withdrawAmount.value)
  const maxWithdrawable = parseFloat(savingsStore.userAssetValue)
  return amount > 0 && amount <= maxWithdrawable
})

const withdrawPreviewFee = computed(() => {
  const amount = parseFloat(withdrawAmount.value)
  const fee = parseFloat(withdrawPreview.value.fee)
  return (amount * fee).toString()
})

// Debounced preview functions
const debouncedDepositPreview = debounce(async (amount: string) => {
  if (amount && parseFloat(amount) > 0) {
    try {
      depositPreview.value = await savingsStore.previewDeposit(amount)
    } catch (error) {
      console.error('Failed to preview deposit:', error)
    }
  } else {
    depositPreview.value = { shares: '', fee: '0' }
  }
}, 500)

const debouncedWithdrawPreview = debounce(async (amount: string) => {
  if (amount && parseFloat(amount) > 0) {
    try {
      withdrawPreview.value = await savingsStore.previewWithdraw(amount)
    } catch (error) {
      console.error('Failed to preview withdraw:', error)
    }
  } else {
    withdrawPreview.value = { shares: '', assets: '', fee: '0' }
  }
}, 500)

const handleDepositAmountChange = (value: string) => {
  isQuickAmountModeOfDeposit.value = false
  debouncedDepositPreview(value)
}

const handleWithdrawAmountChange = (value: string) => {
  isQuickAmountModeOfWithdraw.value = false
  debouncedWithdrawPreview(value)
}

const setMaxDeposit = () => {
  isQuickAmountModeOfDeposit.value = true;
  depositAmount.value = savingsStore.wrmbBalance
  debouncedDepositPreview(depositAmount.value)
}

const setMaxWithdraw = () => {
  isQuickAmountModeOfWithdraw.value = true
  withdrawAmount.value = savingsStore.userAssetValue
  debouncedWithdrawPreview(withdrawAmount.value)
}

const setDepositPercentage = (percentage: number) => {
  isQuickAmountModeOfDeposit.value = true
  const amount = calculatePercentageAmount(savingsStore.wrmbBalance, percentage)
  depositAmount.value = amount
  debouncedDepositPreview(amount)
}

const setWithdrawPercentage = (percentage: number) => {
  isQuickAmountModeOfWithdraw.value = true
  const amount = calculatePercentageAmount(savingsStore.userAssetValue, percentage)
  withdrawAmount.value = amount
  debouncedWithdrawPreview(amount)
}

const handleDeposit = async () => {
  if (!isDepositValid.value || !walletStore.isConnected) return

  transactionModalTitle.value = t('savings.depositTransaction')
  showTransactionModal.value = true
  currentTransactionStep.value = 0
  transactionStatus.value = 'pending'
  try {
    const amountWei = parseUnits(depositAmount.value, 18)

    // Step 1: Check and approve WRMB if needed
    const wrmbContract = contractService.getWRMBContract(true)
    const savingsContract = contractService.getSavingsVaultContract(true)

    if (!wrmbContract || !savingsContract) {
      throw new Error('Contract not available')
    }

    const savingsAddress = await savingsContract.getAddress()
    const allowance = await wrmbContract.allowance(walletStore.address, savingsAddress)

    if (allowance < amountWei) {
      transactionStatus.value = 'loading'
      const approveTx = await wrmbContract.approve(savingsAddress, amountWei)
      await approveTx.wait()
    }

    currentTransactionStep.value = 1

    // Step 2: Execute deposit
    transactionStatus.value = 'loading'
    const depositTx = await savingsContract.deposit(amountWei, walletStore.address)
    currentTransactionStep.value = 2
    isQuickAmountModeOfDeposit.value = false
    const receipt = await depositTx.wait()

    currentTransactionStep.value = 3
    transactionStatus.value = 'success'
    transactionHash.value = receipt.hash

    // Reset form and refresh data
    depositAmount.value = ''
    depositPreview.value = { shares: '', fee: '0' }
    await savingsStore.fetchVaultData()
    ElMessage.success(t('savings.depositSuccess'))
  } catch (error: any) {
    transactionStatus.value = 'error'
    transactionError.value = error.message || t('savings.depositFailed')
    console.error('Deposit failed:', error)
  }
}

const handleWithdraw = async () => {
  if (!isWithdrawValid.value || !walletStore.isConnected) return

  // 检查手续费是否超过10%，需要二次确认
  const feePercentage = parseFloat(withdrawPreview.value.fee) * 100
  if (feePercentage > 10) {
    const confirmed = await ElMessageBox.confirm(
      `${t('savings.highFeeWarning')} ${formatNumber(feePercentage.toString(), 2)}%。${t('savings.confirmHighFeeWithdraw')}`,
      t('savings.highFeeTitle'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning',
        dangerouslyUseHTMLString: false
      }
    ).catch(() => false)

    if (!confirmed) {
      return
    }
  }

  transactionModalTitle.value = t('savings.withdrawTransaction')
  showTransactionModal.value = true
  currentTransactionStep.value = 1
  transactionStatus.value = 'loading'

  try {
    const amountWei = parseUnits(withdrawAmount.value, 18)

    // Execute withdraw
    const savingsContract = contractService.getSavingsVaultContract(true)
    if (!savingsContract) {
      throw new Error('Contract not available')
    }

    if (withdrawAmount.value === savingsStore.userAssetValue) {
      const withdrawTx = await savingsContract.redeem(
        parseUnits(savingsStore.userBalance, 18),
        walletStore.address,
        walletStore.address
      )
      currentTransactionStep.value = 2
      isQuickAmountModeOfWithdraw.value = false
      const receipt = await withdrawTx.wait()

      currentTransactionStep.value = 3
      transactionStatus.value = 'success'
      transactionHash.value = receipt.hash
    } else {
      const withdrawTx = await savingsContract.withdraw(
        amountWei,
        walletStore.address,
        walletStore.address
      )
      currentTransactionStep.value = 2
      isQuickAmountModeOfWithdraw.value = false
      const receipt = await withdrawTx.wait()

      currentTransactionStep.value = 3
      transactionStatus.value = 'success'
      transactionHash.value = receipt.hash
    }


    // Reset form and refresh data
    withdrawAmount.value = ''
    withdrawPreview.value = { shares: '', assets: '', fee: '0' }
    await savingsStore.fetchVaultData()
    ElMessage.success(t('savings.withdrawSuccess'))
  } catch (error: any) {
    transactionStatus.value = 'error'
    transactionError.value = error.message || t('savings.withdrawFailed')
    console.error('Withdraw failed:', error)
  }
}

const handleTransactionModalClose = () => {
  showTransactionModal.value = false
  transactionHash.value = ''
  transactionError.value = ''
}

const handleTransactionRetry = () => {
  if (activeTab.value === 'deposit') {
    handleDeposit()
  } else {
    handleWithdraw()
  }
}

const refreshData = async () => {
  await Promise.all([
    savingsStore.fetchVaultData(),
    savingsStore.fetchUserBalances(),
    savingsStore.fetchWRMBPrice()
  ])
}

// Pull to refresh functionality
const { isRefreshing, pullDistance, isPulling, canRefresh } = usePullToRefresh({
  onRefresh: refreshData,
  enabled: true
})

onMounted(async () => {
  if (walletStore.isConnected) {
    await refreshData()
    savingsStore.startAutoRefresh()
  } else {
    // Even if wallet is not connected, fetch basic vault data and price
    await savingsStore.fetchVaultData()
  }
})

watch(
  () => savingsStore.wrmbBalance,
  (newBalance) => {
    if (isQuickAmountModeOfDeposit.value) {
      depositAmount.value = newBalance
      debouncedDepositPreview(newBalance)
    }
  }
)

watch(
  () => savingsStore.userAssetValue,
  (newValue) => {
    if (isQuickAmountModeOfWithdraw.value) {
      withdrawAmount.value = newValue
      debouncedWithdrawPreview(newValue)
    }
  }
)

// Watch for wallet connection changes
watch(
  () => walletStore.isConnected,
  async (connected) => {
    if (connected) {
      await refreshData()
      savingsStore.startAutoRefresh()
    } else {
      savingsStore.stopAutoRefresh()
    }
  }
)

// Watch for chainId changes
watch(
  () => walletStore.chainId,
  async (chainId) => {
    if (chainId) {
      await refreshData()
    }
  }
)

// Watch for tab changes and reset input fields
watch(activeTab, (newTab) => {
  // Reset input amounts and previews when switching tabs
  depositAmount.value = ''
  withdrawAmount.value = ''
  depositPreview.value = { shares: '', fee: '0' }
  withdrawPreview.value = { shares: '', assets: '', fee: '0' }
})
</script>

<style scoped>
.section {
  margin-left: 4rem;
  padding-top: 2rem;
}

.section-title {
  font-size: 24px;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 24px;
}

.overview-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 24px;
}

.overview-card {
  background-color: var(--card-bg);
  border-radius: 12px;
  padding: 24px;
  transition: all 0.2s ease;
}

.overview-card.highlight {
  background: linear-gradient(135deg, var(--primary-color), var(--accent-color));
  color: white;
  border-color: var(--primary-color);
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}

.card-title {
  font-size: 14px;
  font-weight: 500;
  color: var(--text-secondary);
}

.overview-card.highlight .card-title {
  color: rgba(255, 255, 255, 0.8);
}

.card-icon {
  font-size: 20px;
  color: var(--text-secondary);
}

.overview-card.highlight .card-icon {
  color: rgba(255, 255, 255, 0.6);
}

.card-value {
  font-size: 24px;
  font-weight: 700;
  color: var(--number-color);
  display: flex;
  align-items: center;
  gap: 8px;
}

.wrmb-icon {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
}

.animated-number {
  display: flex;
  align-items: center;
}

.overview-card.highlight .card-value {
  color: white;
}

.card-subtitle {
  font-size: 14px;
  font-weight: 500;
  color: var(--text-secondary);
}

.overview-card.highlight .card-subtitle {
  color: rgba(255, 255, 255, 0.8);
}

.action-section {
  background-color: var(--card-bg);
  border-radius: 12px;
  margin-top: 24px;
}

.savings-tabs {
  padding: 24px;
}

.tab-content {
  margin-top: 24px;
}

.action-form {
  max-width: 448px;
  margin: 0 auto;
}

.form-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24px;
}

.form-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
}

.balance-info {
  font-size: 14px;
}

.balance-label {
  color: var(--text-secondary);
}

.balance-value {
  font-weight: 500;
  color: var(--text-primary);
  margin-left: 4px;
}

.input-section {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-bottom: 24px;
}

.input-group {
  display: flex;
  align-items: center;
  gap: 12px;
}

.amount-input {
  flex: 1;
}

.input-suffix {
  color: var(--text-secondary);
  font-weight: 500;
}

.preview-section {
  background-color: var(--bg-secondary);
  border-radius: 8px;
  padding: 16px;
  margin-bottom: 24px;
}

.preview-title {
  font-size: 14px;
  font-weight: 500;
  color: var(--text-primary);
  margin-bottom: 12px;
}

.preview-details {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.preview-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 14px;
}

.preview-row span:first-child {
  color: var(--text-secondary);
}

.preview-row.exchange-rate {
  border-top: 1px solid var(--border-color);
  padding-top: 8px;
  margin-top: 8px;
}

.preview-row.exchange-rate .preview-value {
  color: var(--accent-color);
  font-weight: 600;
}

.preview-value {
  font-weight: 500;
  color: var(--text-primary);
}

.fee-value {
  color: var(--warning-color);
  font-weight: 500;
}

.action-button {
  width: 100%;
}

.statistics-section {
  background-color: var(--card-bg);
  border-radius: 12px;
  padding: 24px;
  margin-top: 24px;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 24px;
  max-width: 480px;
  margin: 0 auto;
  justify-items: center;
}

@media (min-width: 1024px) {
  .stats-grid {
    grid-template-columns: repeat(4, 1fr);
  }
}

.stat-item {
  text-align: center;
}

.stat-label {
  font-size: 14px;
  color: var(--text-secondary);
  margin-bottom: 8px;
}

.stat-value {
  font-size: 14px;
  font-weight: 700;
  color: var(--number-color);
}

:deep(.el-tabs__header) {
  margin-bottom: 0;
}

:deep(.el-tabs__nav-wrap::after) {
  background-color: var(--border-color);
}

:deep(.el-tabs__active-bar) {
  background-color: var(--primary-color);
  font-weight: 600;
}

:deep(.el-tabs__item) {
  color: var(--text-secondary);
}

:deep(.el-tabs__item.is-active) {
  color: var(--primary-color);
  font-weight: 600;
}

@media (max-width: 768px) {
  .section {
    margin-left: 1rem;
  }

  .overview-grid {
    grid-template-columns: 1fr;
    gap: 16px;
  }

  .stats-grid {
    grid-template-columns: repeat(2, 1fr);
    gap: 16px;
  }

  .action-form {
    max-width: 100%;
  }
}
</style>
