// src/views/Farm.vue
<template>
  <div class="farm-container">
    <PullToRefresh :is-pulling="isPulling" :is-refreshing="isRefreshing" :pull-distance="pullDistance"
      :can-refresh="canRefresh">
      <!-- Farm Overview -->
      <div class="farm-overview">
        <h2 class="section-title">
          {{ $t('farm.overview') }}
        </h2>

        <div class="overview-grid">
          <!-- Your CINA Mined -->
          <div class="overview-card">
            <div class="card-header">
              <h3 class="card-title">{{ $t('farm.yourMined') }}</h3>
              <div class="card-subtitle">
                {{ $t('farm.apy') }} {{ formatNumber(farmStore.farmAPY) }}%
              </div>
            </div>
            <div class="card-value">
              <img src="../assets/logo.png" alt="" class="token-icon">
              <AnimatedNumber class="animated-number" :value="farmStore.pendingCINA"
                :auto-increment="walletStore.isConnected" :increment-amount="parseFloat(farmStore.incrementAmount)"
                :increment-interval="1000" :cache-key="`totalCINAMined_${walletStore.address}`" :use-cache="false" />
            </div>
          </div>
        </div>
      </div>

      <!-- Farm Actions -->
      <div class="action-section">
        <el-tabs v-model="activeTab" class="farm-tabs">
          <!-- Deposit Token Tab -->
          <el-tab-pane :label="$t('farm.deposit')" name="deposit">
            <div class="tab-content">
              <div class="action-form">
                <div class="input-section">
                  <div class="input-group">
                    <div class="input-with-select">
                      <FormattedInput v-model="depositAmount"
                        :placeholder="formatNumberK(farmStore.usdtBalance) + '  ' + $t('available')" size="large"
                        class="amount-input" :decimals="6" :use-abbreviation="true">
                        <TokenSelect v-model="depositToken" :tokens="availableTokens" placeholder="Select token" />
                      </FormattedInput>
                    </div>
                  </div>

                  <!-- Quick Amount Buttons -->
                  <QuickAmounts :max-label="$t('common.max')" @select-percentage="setDepositPercentage"
                    @select-max="setMaxDeposit" />
                </div>

                <!-- Farm Preview -->
                <div v-if="depositPreview" class="preview-section">
                  <h4 class="preview-title">{{ $t('farm.preview') }}</h4>
                  <div class="preview-details">
                    <div class="preview-row">
                      <span>{{ $t('farm.dailyReward') }}</span>
                      <span class="preview-value">{{ formatNumber(depositPreview.dailyReward, 2) }} CINA</span>
                    </div>
                  </div>
                </div>

                <el-button type="primary" size="large" :loading="farmStore.depositInProgress"
                  :disabled="!isDepositValid" @click="handleDeposit" class="action-button">
                  {{ $t('farm.deposit') }}
                </el-button>
              </div>
            </div>
          </el-tab-pane>

          <!-- Withdraw Token Tab -->
          <el-tab-pane :label="$t('farm.withdraw')" name="withdraw">
            <div class="tab-content">
              <div class="action-form">
                <div class="input-section">
                  <div class="input-group">
                    <div class="input-with-select">
                      <FormattedInput v-model="withdrawAmount"
                        :placeholder="formatNumberK(farmStore.depositedAmount) + '  ' + $t('available')" size="large"
                        class="amount-input" :decimals="6" :use-abbreviation="true">
                        <TokenSelect v-model="withdrawToken" :tokens="availableTokens" placeholder="Select token" />
                      </FormattedInput>
                    </div>
                  </div>

                  <!-- Quick Amount Buttons -->
                  <QuickAmounts :max-label="$t('common.max')" @select-percentage="setWithdrawPercentage"
                    @select-max="setMaxWithdraw" />

                  <!-- Claim CINA -->
                  <div class="input-group">
                    <el-checkbox v-model="withdrawCINA" class="withdraw-cina-checkbox"
                      @change="handleWithdrawCINAChange">
                      {{ $t('farm.withdrawCINA') }}
                    </el-checkbox>
                  </div>
                </div>

                <!-- Withdraw Preview -->
                <div v-if="withdrawPreview || withdrawCINA" class="preview-section">
                  <h4 class="preview-title">{{ $t('farm.preview') }}</h4>
                  <div class="preview-details">
                    <div v-if="withdrawPreview" class="preview-row">
                      <span>Liquidity</span>
                      <span class="preview-value liquidity-value">{{ formatNumber(withdrawPreview.liquidityAmount, 2)
                      }} {{
                          withdrawToken?.symbol }}</span>
                    </div>
                    <div v-if="withdrawCINA" class="preview-row">
                      <span>Farm Reward</span>
                      <span class="preview-value">{{ formatNumber(farmStore.pendingCINA, 2) }} CINA</span>
                    </div>
                  </div>
                </div>

                <el-button type="primary" size="large"
                  :loading="farmStore.withdrawInProgress || farmStore.claimInProgress" :disabled="!isWithdrawValid"
                  @click="handleWithdraw" class="action-button">
                  {{ withdrawCINA && (!withdrawAmount || parseFloat(withdrawAmount) === 0) ? $t('farm.claim') :
                    $t('farm.withdraw') }}
                </el-button>
              </div>
            </div>
          </el-tab-pane>
        </el-tabs>
      </div>

      <!-- Info Cards -->
      <InfoCards :cards="infoCards" />
    </PullToRefresh>

    <!-- Transaction Modal -->
    <TransactionModal v-model:visible="showTransactionModal" :title="transactionModalTitle" :steps="transactionSteps"
      :current-step="currentTransactionStep" :status="transactionStatus" :transaction-details="transactionDetails"
      :transaction-hash="transactionHash" :error-message="transactionError" @close="handleTransactionModalClose"
      @retry="handleTransactionRetry" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { parseUnits } from 'ethers'
import { InfoFilled, QuestionFilled, WarningFilled } from '@element-plus/icons-vue'

import AnimatedNumber from '@/components/common/AnimatedNumber.vue'
import TokenSelect from '@/components/TokenSelect.vue'
import QuickAmounts from '@/components/common/QuickAmounts.vue'
import TransactionModal from '@/components/common/TransactionModal.vue'
import PullToRefresh from '@/components/common/PullToRefresh.vue'
import FormattedInput from '@/components/common/FormattedInput.vue'
import InfoCards from '@/components/common/InfoCards.vue'
import { usePullToRefresh } from '@/composables/usePullToRefresh'
import { useWalletStore } from '@/stores/wallet'
import { useFarmStore } from '@/stores/farm'
import { contractService } from '@/services/contracts'
import { formatNumber, formatNumberK } from '@/utils/format'
import { TOKENS } from '@/constants'

// Define types
interface Token {
  symbol: string
  name: string
  address: string
  decimals: number
}

const { t } = useI18n()
const walletStore = useWalletStore()
const farmStore = useFarmStore()

// Pull to refresh functionality
const { isRefreshing, pullDistance, isPulling, canRefresh, ...touchHandlers } = usePullToRefresh({
  onRefresh: async (): Promise<void> => {
    if (walletStore.isConnected) {
      await farmStore.fetchFarmData()
      await farmStore.fetchUserFarmData()
    }
  }
})

// Available tokens for farm
const availableTokens = computed<Token[]>(() => {
  const chainId = walletStore.chainId || 11155111

  return [
    {
      symbol: TOKENS.USDT.symbol,
      name: TOKENS.USDT.name,
      address: TOKENS.USDT.addresses[chainId as keyof typeof TOKENS.USDT.addresses] || TOKENS.USDT.addresses[11155111] || '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
      decimals: TOKENS.USDT.decimals
    },
    // {
    //   symbol: TOKENS.USDC.symbol,
    //   name: TOKENS.USDC.name,
    //   address: TOKENS.USDC.addresses[chainId as keyof typeof TOKENS.USDC.addresses] || TOKENS.USDC.addresses[11155111] || '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
    //   decimals: TOKENS.USDC.decimals
    // }
  ]
})

const activeTab = ref('deposit')
const depositAmount = ref('')
const withdrawAmount = ref('')
const withdrawCINA = ref(false) // 是否同时提取CINA的开关
const depositToken = ref<Token>()
const withdrawToken = ref<Token>()

// Info Cards data
const infoCards = computed(() => [
  {
    icon: InfoFilled,
    title: t('farm.whatIsFarming'),
    content: t('farm.farmingDescription')
  },
  {
    icon: QuestionFilled,
    title: t('farm.farmingFees'),
    content: t('farm.farmingFeesDescription')
  },
  {
    icon: WarningFilled,
    title: t('farm.farmingRisks'),
    content: t('farm.farmingRisksDescription')
  }
])

// Transaction Modal
const showTransactionModal = ref(false)
const transactionModalTitle = ref('')
const currentTransactionStep = ref(0)
const transactionStatus = ref<'pending' | 'loading' | 'success' | 'error'>('pending')
const transactionHash = ref('')
const transactionError = ref('')

const transactionSteps = ref([
  { label: t('transaction.approve'), description: t('transaction.approveDescription') },
  { label: t('transaction.confirm'), description: t('transaction.confirmDescription') },
  { label: t('transaction.complete'), description: t('transaction.completeDescription') }
])

const transactionDetails = computed(() => {
  const details: {
    label: string
    values: string[]
    highlight?: boolean
    type?: 'debit' | 'credit'
  }[] = []

  if (activeTab.value === 'deposit' && depositAmount.value && parseFloat(depositAmount.value) > 0) {
    details.push(
      { label: t('pay'), values: [`-${formatNumber(depositAmount.value, 6)} USDT`], highlight: true, type: 'debit' }
    )
  } else if (activeTab.value === 'withdraw') {
    const values = [];
    if (withdrawCINA.value && parseFloat(farmStore.pendingCINA) > 0) {
      values.push(`+${formatNumber(farmStore.pendingCINA, 6)} CINA`)
    }
    if (withdrawAmount.value && parseFloat(withdrawAmount.value) > 0) {
      values.push(`+${formatNumber(withdrawAmount.value, 6)} USDT`);
    }
    details.push(
      { label: t('receive'), values, type: 'credit' }
    )
  }

  return details
})

// Initialize tokens
watch(availableTokens, (tokens) => {
  if (tokens.length >= 1) {
    if (!depositToken.value || depositToken.value.symbol !== tokens[0].symbol) {
      depositToken.value = tokens[0]
    }
    if (!withdrawToken.value || withdrawToken.value.symbol !== tokens[0].symbol) {
      withdrawToken.value = tokens[0]
    }
  }
}, { immediate: true })

// Computed properties
const isDepositValid = computed(() => {
  const amount = parseFloat(depositAmount.value)
  return amount > 0 && amount <= parseFloat(farmStore.usdtBalance)
})

const isWithdrawValid = computed(() => {
  const amount = parseFloat(withdrawAmount.value)
  // 如果勾选了withdrawCINA但没有输入金额，只要有可claim的CINA就有效
  if (withdrawCINA.value && (!withdrawAmount.value || amount === 0)) {
    return parseFloat(farmStore.pendingCINA) > 0
  }
  // 如果有输入金额，检查金额是否有效
  return amount > 0 && amount <= parseFloat(farmStore.depositedAmount)
})

const depositPreview = computed(() => {
  const amount = parseFloat(depositAmount.value)
  if (!amount || amount <= 0) return null

  const exchangeRate = parseFloat(farmStore.exchangeRate)
  const estimatedCINA = amount * exchangeRate
  const dailyReward = estimatedCINA * parseFloat(farmStore.farmAPY) / 365 / 100

  return {
    estimatedCINA,
    dailyReward
  }
})

const withdrawPreview = computed(() => {
  const amount = parseFloat(withdrawAmount.value)
  if (!amount || amount <= 0) return null

  return {
    rewardAmount: farmStore.pendingCINA,
    liquidityAmount: farmStore.liquidityAmount
  }
})

const setDepositPercentage = (percentage: number) => {
  const balance = parseFloat(farmStore.usdtBalance)
  const amount = (balance * percentage / 100).toFixed(6)
  depositAmount.value = amount
}

const setMaxDeposit = () => {
  depositAmount.value = farmStore.usdtBalance
}

const handleDeposit = async () => {
  if (!isDepositValid.value || !walletStore.isConnected) return

  transactionModalTitle.value = t('savings.depositTransaction')
  showTransactionModal.value = true
  currentTransactionStep.value = 0
  transactionStatus.value = 'pending'

  try {
    const amount = parseFloat(depositAmount.value)
    const amountWei = parseUnits(amount.toString(), 6) // USDT has 6 decimals

    // Step 1: Check and approve USDT if needed
    transactionStatus.value = 'loading'

    const usdtContract = contractService.getUSDTContract(true)
    const farmContract = contractService.getFarmVaultContract(true)

    if (!usdtContract || !farmContract) {
      throw new Error('Contract not available')
    }

    const farmAddress = await farmContract.getAddress()
    const allowance = await usdtContract.allowance(walletStore.address, farmAddress)

    // Check and approve USDT if needed
    if (allowance < amountWei) {
      const approveTx = await usdtContract.approve(farmAddress, amountWei)
      await approveTx.wait()
    }

    currentTransactionStep.value = 1

    // Step 2: Execute deposit
    const depositTx = await farmContract.deposit(amountWei)
    currentTransactionStep.value = 2
    const receipt = await depositTx.wait()

    currentTransactionStep.value = 3
    transactionStatus.value = 'success'
    transactionHash.value = receipt.hash

    // Reset form and refresh data
    depositAmount.value = ''
    await farmStore.fetchFarmData()
    await farmStore.fetchUserFarmData()
    ElMessage.success(t('farm.depositSuccess'))
  } catch (error: any) {
    transactionStatus.value = 'error'
    transactionError.value = error.message || t('farm.depositFailed')
    console.error('Deposit failed:', error)
  }
}

const setWithdrawPercentage = (percentage: number) => {
  const balance = parseFloat(farmStore.depositedAmount)
  const amount = (balance * percentage / 100).toFixed(6)
  withdrawAmount.value = amount
}

const setMaxWithdraw = () => {
  withdrawAmount.value = farmStore.depositedAmount
}

const handleWithdraw = async () => {
  if (!walletStore.isConnected) return

  transactionModalTitle.value = t('savings.withdrawTransaction')
  showTransactionModal.value = true
  currentTransactionStep.value = 1
  transactionStatus.value = 'pending'

  try {
    const amount = parseFloat(withdrawAmount.value)
    transactionStatus.value = 'loading'

    const farmContract = contractService.getFarmVaultContract(true)
    if (!farmContract) {
      throw new Error('Farm contract not available')
    }

    // 如果勾选了withdrawCINA但没有输入金额，只执行claim
    if (withdrawCINA.value && (!withdrawAmount.value || amount === 0)) {
      if (parseFloat(farmStore.pendingCINA) > 0) {
        // Execute getReward to claim CINA rewards
        const claimTx = await farmContract.getReward()
        currentTransactionStep.value = 2
        const receipt = await claimTx.wait()

        currentTransactionStep.value = 3
        transactionStatus.value = 'success'
        transactionHash.value = receipt.hash
        ElMessage.success(t('farm.claimSuccess'))
      }
    } else {
      // 执行USDT提现
      const amountWei = parseUnits(amount.toString(), 6) // USDT has 6 decimals
      // Execute withdraw with isClaim=false (only withdraw, don't claim rewards)
      const withdrawTx = await farmContract.withdraw(amountWei, withdrawCINA.value ? 1 : 0)
      currentTransactionStep.value = 2
      const receipt = await withdrawTx.wait()

      currentTransactionStep.value = 3
      transactionStatus.value = 'success'
      transactionHash.value = receipt.hash
      ElMessage.success(t('farm.withdrawSuccess'))
    }

    withdrawAmount.value = ''
    withdrawCINA.value = false // 重置开关状态

    // Refresh data
    await farmStore.fetchFarmData()
    await farmStore.fetchUserFarmData()
  } catch (error: any) {
    transactionStatus.value = 'error'
    transactionError.value = error.message || t('farm.withdrawFailed')
    console.error('Withdraw failed:', error)
  }
}

const handleTransactionModalClose = () => {
  showTransactionModal.value = false
  transactionHash.value = ''
  transactionError.value = ''
}

const handleTransactionRetry = () => {
  if (activeTab.value === 'deposit') {
    handleDeposit()
  } else {
    handleWithdraw()
  }
}

const handleWithdrawCINAChange = async () => {
  if (walletStore.isConnected) {
    await farmStore.fetchFarmData()
  }
}

// Lifecycle
onMounted(async () => {
  if (walletStore.isConnected) {
    await farmStore.fetchFarmData()
    await farmStore.startAutoRefresh();
  }
})

// Watch for wallet connection changes
watch(
  () => walletStore.isConnected,
  async (connected) => {
    if (connected) {
      await farmStore.fetchFarmData()
      await farmStore.startAutoRefresh()
    }
  }
)

// Watch for tab changes and reset input fields
watch(activeTab, (newTab) => {
  // Reset input amounts when switching tabs
  depositAmount.value = ''
  withdrawAmount.value = ''
})
</script>

<style scoped>
.farm-container {
  @apply h-full;
}

.section-title {
  @apply text-2xl font-bold mb-6;
  color: var(--text-primary);
}

.overview-grid {
  @apply grid grid-cols-1 gap-6 mb-8;
}

.overview-card {
  @apply rounded-xl p-6;
  background-color: var(--card-bg);
}

.card-header {
  @apply flex items-center justify-between mb-4;
}

.card-title {
  @apply text-sm font-medium;
  color: var(--text-secondary);
}

.card-icon {
  @apply text-xl;
  color: var(--primary-color);
}

.card-value {
  @apply text-2xl font-bold mb-2 flex items-center justify-between gap-2;
  color: var(--number-color);
}

.token-icon {
  @apply w-8 h-8 rounded-full object-cover;
}

.animated-number {
  @apply flex items-center;
}

.card-value .animated-number {
  @apply flex-1;
}

.card-actions {
  @apply mt-4;
}

.token-symbol {
  @apply text-lg font-medium;
  color: var(--text-secondary);
}

.card-subtitle {
  @apply text-sm font-medium;
  color: var(--text-secondary);
}

.action-section {
  @apply rounded-xl mb-8;
  background-color: var(--card-bg);
}

.farm-tabs {
  @apply p-6;
}

.tab-content {
  @apply mt-6;
}

.action-form {
  @apply space-y-6;
}

.input-section {
  @apply space-y-4;
}

.input-group {
  @apply space-y-2;
}

.amount-input {
  @apply w-full;
}

.input-suffix {
  @apply font-medium;
  color: var(--text-secondary);
}

.max-button {
  @apply hover:opacity-80;
  color: var(--primary-color);
}

.quick-amounts {
  @apply flex space-x-2;
}

.balance-info {
  @apply flex justify-between items-center text-sm;
}

.balance-label {
  color: var(--text-secondary);
}

.balance-value {
  @apply font-medium;
  color: var(--text-primary);
}

.preview-section {
  @apply rounded-lg p-4;
  background-color: var(--bg-secondary);
}

.preview-title {
  @apply text-sm font-medium mb-3;
  color: var(--text-primary);
}

.preview-details {
  @apply space-y-2;
}

.preview-row {
  @apply flex justify-between items-center text-sm;
}

.preview-row span:first-child {
  color: var(--text-secondary);
}

.preview-value {
  @apply font-medium;
  color: var(--text-primary);
}

.preview-row.fee .preview-value {
  color: var(--error-color);
}

.liquidity-value {
  @apply font-medium;
  color: var(--warning-color);
}

.fee-amount {
  color: var(--error-color);
}

.action-button {
  @apply w-full h-12 text-base font-medium;
}

.claim-section {
  @apply space-y-6;
}

.claim-info {
  @apply rounded-lg p-6;
  background: linear-gradient(135deg, var(--card-bg) 0%, var(--bg-primary) 100%);
}

.claim-amount {
  @apply text-center mb-4;
}

.claim-amount h3 {
  @apply text-lg font-medium mb-2;
  color: var(--text-primary);
}

.amount-display {
  @apply text-3xl font-bold flex items-center justify-center gap-2;
  color: var(--primary-color);
}

.claim-details {
  @apply space-y-2;
}

.input-with-select {
  @apply flex w-full;
}

.input-with-select .el-input {
  @apply flex-1;
}

.token-select {
  @apply ml-2 w-32;
}

.token-option {
  @apply flex items-center gap-2;
}

.detail-row {
  @apply flex justify-between items-center text-sm;
}

.detail-row span:first-child {
  color: var(--text-secondary);
}

.detail-row span:last-child {
  @apply font-medium;
  color: var(--text-primary);
}

.claim-button {
  background: linear-gradient(135deg, var(--primary-color) 0%, var(--accent-color) 100%);
}

.claim-button:hover {
  opacity: 0.9;
}

.card-value {
  @apply relative flex items-start justify-between;
}

.value-content {
  @apply flex items-baseline gap-2;
}

.claim-button-corner {
  @apply absolute bottom-0 right-0 text-xs px-2 py-1;
  @apply border-0 rounded-md shadow-sm;
  background: linear-gradient(135deg, var(--primary-color) 0%, var(--accent-color) 100%);
}

.claim-button-corner:hover {
  opacity: 0.9;
}

:deep(.el-tabs__header) {
  @apply mb-0;
}

:deep(.el-tabs__nav-wrap::after) {
  background-color: var(--border-color);
}

:deep(.el-tabs__active-bar) {
  background-color: var(--primary-color);
}

:deep(.el-tabs__item) {
  color: var(--text-secondary);
}

:deep(.el-tabs__item.is-active) {
  color: var(--primary-color);
}

@media (max-width: 768px) {
  .overview-grid {
    @apply grid-cols-1 gap-4;
  }
}
</style>

// src/pages/Farm.tsx
import { InfoCircleOutlined, QuestionCircleOutlined, WarningOutlined } from '@ant-design/icons'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ethers, formatUnits, parseUnits } from 'ethers'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { AnimatedNumber } from '@/components/common/AnimatedNumber'
import { FormattedInput } from '@/components/common/FormattedInput'
import { InfoCards } from '@/components/common/InfoCards'
import { PullToRefresh } from '@/components/common/PullToRefresh'
import { QuickAmounts } from '@/components/common/QuickAmounts'
import { TokenIcon } from '@/components/common/TokenIcon'
import { TransactionModal, type TransactionDetail, type TransactionStep } from '@/components/common/TransactionModal'
import { DEFAULT_CHAIN_ID } from '@/constants'
import { feedback } from '@/lib/feedback'
import { PageScaffold, PageSection } from '@/pages/PageScaffold'
import { contractService } from '@/services/contracts'
import { useFarmStore } from '@/stores/farm'
import { useWalletStore } from '@/stores/wallet'
import { calculatePercentageAmount, formatNumber, formatNumberK } from '@/utils/format'
import { resolveText } from '@/utils/i18n'

interface FarmView {
  liquidityAmount: string
  usdtBalance: string
  depositedAmount: string
  pendingCINA: string
  farmAPY: string
  farmRate: string
  exchangeRate: string
}

const emptyFarmView: FarmView = {
  liquidityAmount: '0',
  usdtBalance: '0',
  depositedAmount: '0',
  pendingCINA: '0',
  farmAPY: '0',
  farmRate: '0',
  exchangeRate: '1'
}

export default function FarmPage() {
  const { t } = useTranslation()
  const wallet = useWalletStore()
  const queryClient = useQueryClient()
  const activeTab = useFarmStore(state => state.activeTab)
  const setActiveTab = useFarmStore(state => state.setActiveTab)
  const chainId = wallet.chainId || DEFAULT_CHAIN_ID

  const [depositAmount, setDepositAmount] = useState('')
  const [withdrawAmount, setWithdrawAmount] = useState('')
  const [withdrawCINA, setWithdrawCINA] = useState(false)
  const [transactionVisible, setTransactionVisible] = useState(false)
  const [transactionTitle, setTransactionTitle] = useState('')
  const [transactionHash, setTransactionHash] = useState('')
  const [transactionError, setTransactionError] = useState('')
  const [transactionStatus, setTransactionStatus] = useState<'pending' | 'loading' | 'success' | 'error'>('pending')
  const [transactionStep, setTransactionStep] = useState(0)

  const farmQuery = useQuery({
    queryKey: ['farm', 'overview', chainId, wallet.address],
    refetchInterval: wallet.isConnected ? 6_000 : 30_000,
    queryFn: async (): Promise<FarmView> => {
      const farmVaultContract = contractService.getFarmVaultContract()
      const usdtContract = contractService.getUSDTContract()
      if (!farmVaultContract || !usdtContract) {
        return emptyFarmView
      }

      const farmAddress = await farmVaultContract.getAddress()
      const [totalSupply, rewardRate, earnedAmount, userBalance, liquidityAmount, userUsdtBalance] = await Promise.all([
        farmVaultContract.totalSupply().catch(() => 0n),
        farmVaultContract.rewardRate().catch(() => 0n),
        wallet.address ? farmVaultContract.earned(wallet.address).catch(() => 0n) : 0n,
        wallet.address ? farmVaultContract.balanceOf(wallet.address).catch(() => 0n) : 0n,
        usdtContract.balanceOf(farmAddress).catch(() => 0n),
        wallet.address ? usdtContract.balanceOf(wallet.address).catch(() => 0n) : 0n
      ])

      const farmRate = formatUnits(rewardRate, 18)
      const totalSupplyFormatted = Number.parseFloat(formatUnits(totalSupply, 6))
      const annualRewards = Number.parseFloat(farmRate) * 365 * 24 * 60 * 60

      return {
        depositedAmount: formatUnits(userBalance, 6),
        exchangeRate: '1',
        farmAPY: totalSupplyFormatted > 0 ? ((annualRewards / totalSupplyFormatted) * 100).toFixed(2) : '0',
        farmRate,
        liquidityAmount: formatUnits(liquidityAmount, 6),
        pendingCINA: formatUnits(earnedAmount, 18),
        usdtBalance: formatUnits(userUsdtBalance, 6)
      }
    }
  })

  const farmView = farmQuery.data ?? emptyFarmView

  const depositPreview = useMemo(() => {
    const amount = Number.parseFloat(depositAmount)
    if (!amount || amount <= 0) {
      return null
    }

    const estimatedCINA = amount * Number.parseFloat(farmView.exchangeRate)
    const dailyReward = (estimatedCINA * Number.parseFloat(farmView.farmAPY || '0')) / 365 / 100
    return {
      estimatedCINA,
      dailyReward
    }
  }, [depositAmount, farmView.exchangeRate, farmView.farmAPY])

  const isDepositValid =
    Number.parseFloat(depositAmount) > 0 && Number.parseFloat(depositAmount) <= Number.parseFloat(farmView.usdtBalance)

  const isWithdrawValid = useMemo(() => {
    const amount = Number.parseFloat(withdrawAmount)
    if (withdrawCINA && (!withdrawAmount || amount === 0)) {
      return Number.parseFloat(farmView.pendingCINA) > 0
    }
    return amount > 0 && amount <= Number.parseFloat(farmView.depositedAmount)
  }, [farmView.depositedAmount, farmView.pendingCINA, withdrawAmount, withdrawCINA])

  const infoCards = useMemo(
    () => [
      {
        icon: <InfoCircleOutlined />,
        title: t('farm.whatIsFarming'),
        content: t('farm.farmingDescription')
      },
      {
        icon: <QuestionCircleOutlined />,
        title: t('farm.farmingFees'),
        content: t('farm.farmingFeesDescription')
      },
      {
        icon: <WarningOutlined />,
        title: t('farm.farmingRisks'),
        content: t('farm.farmingRisksDescription')
      }
    ],
    [t]
  )

  const transactionSteps: TransactionStep[] = useMemo(
    () => [
      { label: t('transaction.approve'), description: t('transaction.approveDescription') },
      { label: t('transaction.confirm'), description: t('transaction.confirmDescription') },
      { label: t('transaction.complete'), description: t('transaction.completeDescription') }
    ],
    [t]
  )

  const transactionDetails = useMemo<TransactionDetail[]>(() => {
    if (activeTab === 'deposit' && Number.parseFloat(depositAmount) > 0) {
      return [
        {
          label: t('pay'),
          values: [`-${formatNumber(depositAmount, 6)} USDT`],
          highlight: true,
          type: 'debit'
        }
      ]
    }

    if (activeTab === 'withdraw') {
      const values: string[] = []
      if (withdrawCINA && Number.parseFloat(farmView.pendingCINA) > 0) {
        values.push(`+${formatNumber(farmView.pendingCINA, 6)} CINA`)
      }
      if (Number.parseFloat(withdrawAmount) > 0) {
        values.push(`+${formatNumber(withdrawAmount, 6)} USDT`)
      }
      return [
        {
          label: t('receive'),
          values,
          type: 'credit'
        }
      ]
    }

    return []
  }, [activeTab, depositAmount, farmView.pendingCINA, t, withdrawAmount, withdrawCINA])

  const refreshData = async () => {
    await queryClient.invalidateQueries({ queryKey: ['farm'] })
  }

  const resetTransaction = () => {
    setTransactionVisible(false)
    setTransactionHash('')
    setTransactionError('')
    setTransactionStatus('pending')
    setTransactionStep(0)
  }

  const handleDeposit = async () => {
    if (!wallet.isConnected || !wallet.address || !isDepositValid) {
      return
    }

    const usdtContract = contractService.getUSDTContract(true)
    const farmContract = contractService.getFarmVaultContract(true)
    if (!usdtContract || !farmContract) {
      feedback.error(t('farm.depositFailed'))
      return
    }

    setTransactionVisible(true)
    setTransactionTitle(t('savings.depositTransaction'))
    setTransactionStatus('pending')
    setTransactionStep(0)

    try {
      const amountWei = parseUnits(depositAmount, 6)
      const farmAddress = await farmContract.getAddress()
      const allowance = await usdtContract.allowance(wallet.address, farmAddress)
      if (allowance < amountWei) {
        setTransactionStatus('loading')
        const approveTx = await usdtContract.approve(farmAddress, ethers.MaxUint256)
        await approveTx.wait()
      }

      setTransactionStep(1)
      setTransactionStatus('loading')
      const depositTx = await farmContract.deposit(amountWei)
      const receipt = await depositTx.wait()

      setTransactionStep(2)
      setTransactionStatus('success')
      setTransactionHash(receipt.hash)
      setDepositAmount('')
      await refreshData()
      feedback.success(t('farm.depositSuccess'))
    } catch (error) {
      setTransactionStatus('error')
      setTransactionError(error instanceof Error ? error.message : t('farm.depositFailed'))
    }
  }

  const handleWithdraw = async () => {
    if (!wallet.isConnected || !isWithdrawValid) {
      return
    }

    const farmContract = contractService.getFarmVaultContract(true)
    if (!farmContract) {
      feedback.error(t('farm.withdrawFailed'))
      return
    }

    setTransactionVisible(true)
    setTransactionTitle(t('savings.withdrawTransaction'))
    setTransactionStatus('pending')
    setTransactionStep(0)

    try {
      setTransactionStatus('loading')

      if (withdrawCINA && (!withdrawAmount || Number.parseFloat(withdrawAmount) === 0)) {
        const claimTx = await farmContract.getReward()
        setTransactionStep(1)
        const receipt = await claimTx.wait()
        setTransactionStep(2)
        setTransactionStatus('success')
        setTransactionHash(receipt.hash)
        feedback.success(t('farm.claimSuccess'))
      } else {
        const amountWei = parseUnits(withdrawAmount, 6)
        const withdrawTx = await farmContract.withdraw(amountWei, withdrawCINA)
        setTransactionStep(1)
        const receipt = await withdrawTx.wait()
        setTransactionStep(2)
        setTransactionStatus('success')
        setTransactionHash(receipt.hash)
        feedback.success(t('farm.withdrawSuccess'))
      }

      setWithdrawAmount('')
      setWithdrawCINA(false)
      await refreshData()
    } catch (error) {
      setTransactionStatus('error')
      setTransactionError(error instanceof Error ? error.message : t('farm.withdrawFailed'))
    }
  }

  const pageTitle = resolveText(t('navigation.farm'), 'navigation.farm', 'Farm')
  const overviewTitle = resolveText(t('farm.overview'), 'farm.overview', 'Overview')
  const connectWalletLabel = resolveText(t('wallet.connectWallet'), 'wallet.connectWallet', 'Connect Wallet')
  const depositLabel = resolveText(t('farm.deposit'), 'farm.deposit', 'Deposit')
  const withdrawLabel = resolveText(t('farm.withdraw'), 'farm.withdraw', 'Withdraw')

  return (
    <PageScaffold title={pageTitle}>
      <PullToRefresh isRefreshing={farmQuery.isRefetching}>
        {!wallet.isConnected ? <div className="app-inline-note is-info mb-6">{connectWalletLabel}</div> : null}

        <PageSection>
          <div className="mb-6">
            <h2 className="page-section-title">{overviewTitle}</h2>
          </div>

          <div className="space-y-4">
            <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-6">
              <div className="text-sm font-semibold text-[var(--text-secondary)]">
                {resolveText(t('farm.yourMined'), 'farm.yourMined', 'Your Mined')}
              </div>
              <div className="mt-4 flex items-center gap-3 text-3xl font-bold text-[var(--number-color)]">
                <TokenIcon size="large" symbol="CINA" />
                <AnimatedNumber decimals={4} value={farmView.pendingCINA} />
              </div>
              <div className="mt-2 text-sm text-[var(--text-secondary)]">
                {resolveText(t('farm.apy'), 'farm.apy', 'APY')} {formatNumber(farmView.farmAPY, 2)}%
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-3">
              <div className="rounded-2xl bg-[var(--card-bg)] p-4">
                <div className="text-sm text-[var(--text-secondary)]">{resolveText(t('farm.usdtBalance'), 'farm.usdtBalance', 'USDT Balance')}</div>
                <div className="mt-2 font-semibold text-[var(--text-primary)]">{formatNumberK(farmView.usdtBalance)}</div>
              </div>
              <div className="rounded-2xl bg-[var(--card-bg)] p-4">
                <div className="text-sm text-[var(--text-secondary)]">{resolveText(t('farm.depositedBalance'), 'farm.depositedBalance', 'Deposited')}</div>
                <div className="mt-2 font-semibold text-[var(--text-primary)]">{formatNumberK(farmView.depositedAmount)}</div>
              </div>
              <div className="rounded-2xl bg-[var(--card-bg)] p-4">
                <div className="text-sm text-[var(--text-secondary)]">{resolveText(t('farm.claim'), 'farm.claim', 'Claim')}</div>
                <div className="mt-2 font-semibold text-[var(--text-primary)]">{formatNumberK(farmView.pendingCINA)} CINA</div>
              </div>
            </div>
          </div>
        </PageSection>

        <PageSection>
          <div className="mb-8 flex items-center justify-center rounded-2xl bg-[var(--bg-secondary)] p-1">
            <button
              className={`w-full rounded-xl px-4 py-3 text-sm font-semibold transition ${
                activeTab === 'deposit' ? 'bg-[var(--primary-color)] text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
              type="button"
              onClick={() => {
                setActiveTab('deposit')
                setDepositAmount('')
                setWithdrawAmount('')
              }}
            >
              {depositLabel}
            </button>
            <button
              className={`w-full rounded-xl px-4 py-3 text-sm font-semibold transition ${
                activeTab === 'withdraw' ? 'bg-[var(--primary-color)] text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
              type="button"
              onClick={() => {
                setActiveTab('withdraw')
                setDepositAmount('')
                setWithdrawAmount('')
              }}
            >
              {withdrawLabel}
            </button>
          </div>

          {activeTab === 'deposit' ? (
            <div className="space-y-6">
              <div>
                <div className="mb-3 flex items-center justify-between gap-4 text-sm">
                  <span className="font-medium text-[var(--text-primary)]">{depositLabel}</span>
                  <span className="text-[var(--text-secondary)]">{formatNumberK(farmView.usdtBalance)} available</span>
                </div>
                <FormattedInput
                  className="w-full"
                  decimals={6}
                  maxDecimals={6}
                  modelValue={depositAmount}
                  placeholder={`${formatNumberK(farmView.usdtBalance)} ${t('available')}`}
                  size="large"
                  useAbbreviation
                  onChange={setDepositAmount}
                >
                  <span className="flex items-center gap-2">
                    <TokenIcon size="medium" symbol="USDT" />
                    <span>USDT</span>
                  </span>
                </FormattedInput>
                <div className="mt-4">
                  <QuickAmounts
                    maxLabel={t('common.max')}
                    onSelectMax={() => setDepositAmount(farmView.usdtBalance)}
                    onSelectPercentage={percentage => setDepositAmount(calculatePercentageAmount(farmView.usdtBalance, percentage, 6))}
                  />
                </div>
              </div>

              {depositPreview ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
                  <h3 className="text-base font-semibold text-[var(--text-primary)]">{resolveText(t('farm.preview'), 'farm.preview', 'Preview')}</h3>
                  <div className="mt-4 space-y-3 text-sm">
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[var(--text-secondary)]">{resolveText(t('farm.estimatedCINA'), 'farm.estimatedCINA', 'Estimated CINA')}</span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(depositPreview.estimatedCINA, 2)} CINA</span>
                    </div>
                    <div className="flex items-center justify-between gap-4 border-t border-[var(--border-color)] pt-3">
                      <span className="text-[var(--text-secondary)]">{resolveText(t('farm.dailyReward'), 'farm.dailyReward', 'Daily Reward')}</span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(depositPreview.dailyReward, 2)} CINA</span>
                    </div>
                  </div>
                </div>
              ) : null}

              <button className="app-action-button is-primary w-full" disabled={!isDepositValid || !wallet.isConnected} type="button" onClick={() => void handleDeposit()}>
                {wallet.isConnected ? depositLabel : connectWalletLabel}
              </button>
            </div>
          ) : (
            <div className="space-y-6">
              <div>
                <div className="mb-3 flex items-center justify-between gap-4 text-sm">
                  <span className="font-medium text-[var(--text-primary)]">{withdrawLabel}</span>
                  <span className="text-[var(--text-secondary)]">{formatNumberK(farmView.depositedAmount)} available</span>
                </div>
                <FormattedInput
                  className="w-full"
                  decimals={6}
                  maxDecimals={6}
                  modelValue={withdrawAmount}
                  placeholder={`${formatNumberK(farmView.depositedAmount)} ${t('available')}`}
                  size="large"
                  useAbbreviation
                  onChange={setWithdrawAmount}
                >
                  <span className="flex items-center gap-2">
                    <TokenIcon size="medium" symbol="USDT" />
                    <span>USDT</span>
                  </span>
                </FormattedInput>
                <div className="mt-4">
                  <QuickAmounts
                    maxLabel={t('common.max')}
                    onSelectMax={() => setWithdrawAmount(farmView.depositedAmount)}
                    onSelectPercentage={percentage => setWithdrawAmount(calculatePercentageAmount(farmView.depositedAmount, percentage, 6))}
                  />
                </div>
              </div>

              <button
                className="flex w-full items-center justify-between rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] px-4 py-3 text-left"
                type="button"
                onClick={() => setWithdrawCINA(!withdrawCINA)}
              >
                <span className="font-medium text-[var(--text-primary)]">{resolveText(t('farm.withdrawCINA'), 'farm.withdrawCINA', 'Withdraw CINA')}</span>
                <span className={`relative h-6 w-11 rounded-full transition ${withdrawCINA ? 'bg-[var(--primary-color)]' : 'bg-[var(--card-bg)]'}`}>
                  <span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${withdrawCINA ? 'left-6' : 'left-1'}`} />
                </span>
              </button>

              {(withdrawCINA || Number.parseFloat(withdrawAmount) > 0) ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
                  <h3 className="text-base font-semibold text-[var(--text-primary)]">{resolveText(t('farm.preview'), 'farm.preview', 'Preview')}</h3>
                  <div className="mt-4 space-y-3 text-sm">
                    {Number.parseFloat(withdrawAmount) > 0 ? (
                      <div className="flex items-center justify-between gap-4">
                        <span className="text-[var(--text-secondary)]">Liquidity</span>
                        <span className="font-medium text-[var(--text-primary)]">{formatNumber(withdrawAmount, 2)} USDT</span>
                      </div>
                    ) : null}
                    {withdrawCINA ? (
                      <div className="flex items-center justify-between gap-4">
                        <span className="text-[var(--text-secondary)]">Farm Reward</span>
                        <span className="font-medium text-[var(--text-primary)]">{formatNumber(farmView.pendingCINA, 2)} CINA</span>
                      </div>
                    ) : null}
                  </div>
                </div>
              ) : null}

              <button className="app-action-button is-primary w-full" disabled={!isWithdrawValid || !wallet.isConnected} type="button" onClick={() => void handleWithdraw()}>
                {wallet.isConnected
                  ? withdrawCINA && (!withdrawAmount || Number.parseFloat(withdrawAmount) === 0)
                    ? resolveText(t('farm.claim'), 'farm.claim', 'Claim')
                    : withdrawLabel
                  : connectWalletLabel}
              </button>
            </div>
          )}
        </PageSection>

        <InfoCards cards={infoCards} />
      </PullToRefresh>

      <TransactionModal
        currentStep={transactionStep}
        errorMessage={transactionError}
        status={transactionStatus}
        steps={transactionSteps}
        title={transactionTitle}
        transactionDetails={transactionDetails}
        transactionHash={transactionHash}
        visible={transactionVisible}
        onClose={resetTransaction}
        onRetry={() => {
          if (activeTab === 'deposit') {
            void handleDeposit()
          } else {
            void handleWithdraw()
          }
        }}
      />
    </PageScaffold>
  )
}
