// src/views/Staking.vue
<template>
  <div class="h-full">
    <PullToRefresh :is-pulling="isPulling" :is-refreshing="isRefreshing" :pull-distance="pullDistance"
      :can-refresh="canRefresh">
      <!-- Staking Overview -->
      <div class="staking-overview">
        <h2 class="section-title">
          {{ $t('staking.overview') }}
        </h2>

        <div class="overview-grid">
          <!-- Your Staked -->
          <div class="overview-card">
            <div class="card-header">
              <h3 class="card-title">{{ $t('staking.yourStaked') }}</h3>
              <div class="card-subtitle">
                {{ $t('staking.apy') }} {{ formatNumber(stakingStore.currentAPY) }}%
              </div>
            </div>
            <div class="card-value">
              <img src="../assets/logo.png" alt="" class="token-icon">
              <AnimatedNumber class="animated-number" :value="stakingStore.yourStaked"
                :auto-increment="walletStore.isConnected && parseFloat(stakingStore.yourStaked) > 0"
                :increment-amount="parseFloat(stakingStore.incrementAmount)" :increment-interval="1000"
                :cache-key="`yourStaked_${walletStore.address}`" :use-cache="false" />
            </div>
          </div>
        </div>
      </div>

      <!-- Staking Actions -->
      <div class="action-section">
        <el-tabs v-model="activeTab" class="staking-tabs">
          <!-- Stake CINA Tab -->
          <el-tab-pane :label="$t('staking.stakeCINA')" name="stake">
            <div class="tab-content">
              <div class="action-form">
                <div class="input-section">
                  <div class="input-group">
                    <FormattedInput v-model="stakeAmount"
                      :placeholder="formatNumberK(stakingStore.cinaBalance, 6) + '  available'" size="large"
                      class="amount-input" :decimals="6" :use-abbreviation="true" :max-decimals="18"
                      @input-change="handleStakeAmountChange">
                      <div class="token-symbol-selected">
                        <TokenIcon symbol="CINA" size="medium" />
                        <span class="token-symbol-text">CINA</span>
                      </div>
                    </FormattedInput>
                  </div>

                  <!-- Quick Amount Buttons -->
                  <QuickAmounts :max-label="$t('common.max')" @select-percentage="setStakePercentage"
                    @select-max="setMaxStake" />

                  <!-- Minimum Stake Warning -->
                  <div v-if="showMinStakeWarning" class="warning-info">
                    <el-icon>
                      <Warning />
                    </el-icon>
                    <span>{{ $t('staking.minStakeWarning', { amount: formatNumber(stakingStore.minStakeAmount) })
                    }}</span>
                  </div>
                </div>

                <!-- Staking Preview -->
                <div v-if="stakePreviewData?.shares" class="preview-section">
                  <h4 class="preview-title">{{ $t('staking.preview') }}</h4>
                  <div class="preview-details">
                    <div class="preview-row">
                      <span>{{ $t('staking.youWillReceive') }}</span>
                      <span class="preview-value">{{ formatNumber(stakePreviewData.shares, 2) }} stCINA</span>
                    </div>
                    <div class="preview-row exchange-rate">
                      <span>{{ $t('staking.exchangeRate') }}</span>
                      <span class="preview-value">1 CINA ≈ {{ formatNumber((1 / parseFloat(stakingStore.navCina)),
                        6)
                      }} stCINA</span>
                    </div>
                  </div>
                </div>

                <el-button type="primary" size="large"
                  :loading="transactionStatus === 'loading' && activeTab === 'stake'" :disabled="!isStakeValid"
                  @click="handleStake" class="action-button">
                  {{ $t('staking.stakeCINA') }}
                </el-button>
              </div>
            </div>
          </el-tab-pane>

          <!-- Unstake CINA Tab -->
          <el-tab-pane :label="$t('staking.unstakeCINA')" name="unstake">
            <div class="tab-content">
              <div class="action-form">
                <div class="input-section">
                  <div class="input-group">
                    <FormattedInput v-model="unstakeAmount"
                      :placeholder="formatNumberK(stakingStore.stakedAmount, 6) + '  available'" size="large"
                      class="amount-input" :decimals="6" :use-abbreviation="true" :max-decimals="18"
                      @input-change="handleUnstakeAmountChange">
                      <div class="token-symbol-selected">
                        <TokenIcon symbol="CINA" size="medium" />
                        <span class="token-symbol-text">CINA</span>
                      </div>
                    </FormattedInput>
                  </div>

                  <!-- Quick Amount Buttons -->
                  <QuickAmounts :max-label="$t('common.max')" @select-percentage="setUnstakePercentage"
                    @select-max="setMaxUnstake" />

                  <!-- Note: Early unstake penalty not available in current contract -->
                  <div v-if="false" class="warning-info early-unstake">
                    <el-icon>
                      <Warning />
                    </el-icon>
                    <span>{{ $t('staking.earlyUnstakeWarning', { penalty: 0 }) }}</span>
                  </div>
                </div>

                <!-- Unstaking Preview -->
                <div v-if="unstakePreviewData?.shares" class="preview-section">
                  <h4 class="preview-title">{{ $t('staking.preview') }}</h4>
                  <div class="preview-details">
                    <div class="preview-row">
                      <span>{{ $t('staking.required') }}</span>
                      <span class="preview-value">{{ formatNumber(unstakePreviewData.shares, 2) }} stCINA</span>
                    </div>
                    <div class="preview-row exchange-rate">
                      <span>{{ $t('staking.exchangeRate') }}</span>
                      <span class="preview-value">1 stCINA ≈ {{ formatNumber(stakingStore.navCina, 6) }} CINA</span>
                    </div>
                  </div>
                </div>

                <el-button type="primary" size="large"
                  :loading="transactionStatus === 'loading' && activeTab === 'unstake'" :disabled="!isUnstakeValid"
                  @click="handleUnstake" class="action-button">
                  {{ $t('staking.unstakeCINA') }}
                </el-button>
              </div>
            </div>
          </el-tab-pane>

        </el-tabs>
      </div>

      <!-- Information Cards -->
      <InfoCards :cards="infoCards" />
    </PullToRefresh>

    <!-- Transaction Modal -->
    <TransactionModal v-model:visible="showTransactionModal" :title="transactionModalTitle" :steps="transactionSteps"
      :current-step="currentTransactionStep" :status="transactionStatus" :transaction-details="transactionDetails"
      :transaction-hash="transactionHash" :error-message="transactionError" @close="handleTransactionModalClose"
      @retry="handleTransactionRetry" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import {
  Warning
} from '@element-plus/icons-vue'
import { parseUnits } from 'ethers'
import { InfoFilled, QuestionFilled, WarningFilled } from '@element-plus/icons-vue'

import TransactionModal from '@/components/common/TransactionModal.vue'
import AnimatedNumber from '@/components/common/AnimatedNumber.vue'
import PullToRefresh from '@/components/common/PullToRefresh.vue'
import FormattedInput from '@/components/common/FormattedInput.vue'
import QuickAmounts from '@/components/common/QuickAmounts.vue'
import InfoCards from '@/components/common/InfoCards.vue'
import { useWalletStore } from '@/stores/wallet'
import { useStakingStore } from '@/stores/staking'
import { contractService } from '@/services/contracts'
import { formatNumber, formatNumberK, calculatePercentageAmount } from '@/utils/format'
import { debounce } from '@/utils/debounce'
import { usePullToRefresh } from '@/composables/usePullToRefresh'

const { t } = useI18n()
const walletStore = useWalletStore()
const stakingStore = useStakingStore()

const activeTab = ref('stake')
const stakeAmount = ref('')
const unstakeAmount = ref('')
const stakePreviewData = ref({
  shares: '',
  fee: '0'
})
const unstakePreviewData = ref({
  shares: ''
})

// Info Cards data
const infoCards = computed(() => [
  {
    icon: InfoFilled,
    title: t('staking.whatIsStaking'),
    content: t('staking.stakingDescription')
  },
  {
    icon: QuestionFilled,
    title: t('staking.stakingRewards'),
    content: t('staking.stakingRewardsDescription')
  },
  {
    icon: WarningFilled,
    title: t('staking.stakingRisks'),
    content: t('staking.stakingRisksDescription')
  }
])

const isQuickAmountModeOfStake = ref(false)
const isQuickAmountModeOfUnstake = ref(false)

// Transaction Modal
const showTransactionModal = ref(false)
const transactionModalTitle = ref('')
const currentTransactionStep = ref(0)
const transactionStatus = ref<'pending' | 'loading' | 'success' | 'error'>('pending')
const transactionHash = ref('')
const transactionError = ref('')

const transactionSteps = ref([
  { label: t('transaction.approve'), description: t('transaction.approveDescription') },
  { label: t('transaction.confirm'), description: t('transaction.confirmDescription') },
  { label: t('transaction.complete'), description: t('transaction.completeDescription') }
])

const transactionDetails = computed(() => {
  const details: {
    label: string
    values: string[]
    highlight?: boolean
    type?: 'debit' | 'credit'
  }[] = []

  if (activeTab.value === 'stake' && stakeAmount.value) {
    details.push(
      { label: t('pay'), values: [`-${formatNumber(stakeAmount.value, 6)} CINA`], highlight: true, type: 'debit' },
      { label: t('receive'), values: [`+${formatNumber(stakePreviewData.value?.shares || '0', 6)} stCINA`], type: 'credit' }
    )
  } else if (activeTab.value === 'unstake' && unstakeAmount.value) {
    details.push(
      { label: t('pay'), values: [`-${formatNumber(unstakePreviewData.value?.shares || '0', 6)} stCINA`], type: 'debit' },
      { label: t('receive'), values: [`+${formatNumber(unstakeAmount.value, 6)} CINA`], highlight: true, type: 'credit' },
    )
  }

  return details
})

// Computed properties
const isStakeValid = computed(() => {
  const amount = parseFloat(stakeAmount.value)
  return amount > 0 &&
    amount <= parseFloat(stakingStore.cinaBalance) &&
    amount >= parseFloat(stakingStore.minStakeAmount)
})

const isUnstakeValid = computed(() => {
  const amount = parseFloat(unstakeAmount.value)
  return amount > 0 && amount <= parseFloat(stakingStore.stakedAmount)
})

const showMinStakeWarning = computed(() => {
  const amount = parseFloat(stakeAmount.value)
  return amount > 0 && amount < parseFloat(stakingStore.minStakeAmount)
})

// Debounced preview functions
const debouncedStakePreview = debounce(async (amount: string) => {
  if (amount && parseFloat(amount) > 0) {
    try {
      stakePreviewData.value = await stakingStore.previewDeposit(amount)
      console.log(stakePreviewData.value);
    } catch (error) {
      console.error('Failed to preview stake:', error)
    }
  } else {
    stakePreviewData.value = { shares: '', fee: '0' }
  }
}, 500)

const debouncedUnstakePreview = debounce(async (amount: string) => {
  if (amount && parseFloat(amount) > 0) {
    try {
      unstakePreviewData.value = await stakingStore.previewWithdraw(amount)
    } catch (error) {
      console.error('Failed to preview unstake:', error)
    }
  } else {
    unstakePreviewData.value = { shares: '' }
  }
}, 500)

// Methods
const handleStakeAmountChange = (value: string) => {
  isQuickAmountModeOfStake.value = false
  const cleanValue = value.replace(/[^0-9.]/g, '')
  stakeAmount.value = cleanValue
  debouncedStakePreview(cleanValue)
}

const handleUnstakeAmountChange = (value: string) => {
  isQuickAmountModeOfUnstake.value = false
  const cleanValue = value.replace(/[^0-9.]/g, '')
  unstakeAmount.value = cleanValue
  debouncedUnstakePreview(cleanValue)
}

const setStakePercentage = (percentage: number) => {
  isQuickAmountModeOfStake.value = true
  const amount = calculatePercentageAmount(stakingStore.cinaBalance, percentage)
  stakeAmount.value = amount
  debouncedStakePreview(amount)
}

const setMaxStake = () => {
  isQuickAmountModeOfStake.value = true
  stakeAmount.value = stakingStore.cinaBalance
  debouncedStakePreview(stakingStore.cinaBalance)
}

const setUnstakePercentage = (percentage: number) => {
  isQuickAmountModeOfUnstake.value = true
  const amount = calculatePercentageAmount(stakingStore.stakedAmount, percentage)
  unstakeAmount.value = amount
  debouncedUnstakePreview(amount)
}

const setMaxUnstake = () => {
  isQuickAmountModeOfUnstake.value = true
  unstakeAmount.value = stakingStore.stakedAmount
  debouncedUnstakePreview(stakingStore.stakedAmount)
}

const handleStake = async () => {
  if (!isStakeValid.value || !walletStore.isConnected) return

  transactionModalTitle.value = t('staking.stakeTransaction')
  showTransactionModal.value = true
  currentTransactionStep.value = 0
  transactionStatus.value = 'pending'

  try {
    const amountWei = parseUnits(stakeAmount.value, 18)

    // Step 1: Check and approve CINA if needed
    const stakingContract = contractService.getStakingVaultContract(true)
    const cinaContract = contractService.getCINAContract(true)

    if (!stakingContract || !cinaContract) {
      throw new Error('Contract not available')
    }

    const stakingAddress = await stakingContract.getAddress()
    const allowance = await cinaContract.allowance(walletStore.address, stakingAddress)

    if (allowance < amountWei) {
      transactionStatus.value = 'loading'
      const approveTx = await cinaContract.approve(stakingAddress, amountWei)
      await approveTx.wait()
    }

    currentTransactionStep.value = 1

    // Step 2: Execute staking
    transactionStatus.value = 'loading'
    const depositTx = await stakingContract.deposit(amountWei, walletStore.address)
    currentTransactionStep.value = 2
    isQuickAmountModeOfStake.value = false
    const receipt = await depositTx.wait()

    currentTransactionStep.value = 3
    transactionStatus.value = 'success'
    transactionHash.value = receipt.hash

    // Reset form and refresh data
    stakeAmount.value = ''
    await stakingStore.fetchStakingData()
    ElMessage.success(t('staking.stakeSuccess'))
  } catch (error: any) {
    transactionStatus.value = 'error'
    transactionError.value = error.message || t('staking.stakeFailed')
    console.error('Stake failed:', error)
  }
}

const handleUnstake = async () => {
  if (!isUnstakeValid.value || !walletStore.isConnected) return

  transactionModalTitle.value = t('staking.unstakeTransaction')
  showTransactionModal.value = true
  currentTransactionStep.value = 1
  transactionStatus.value = 'loading'

  try {
    const amountWei = parseUnits(unstakeAmount.value, 18)

    // Execute unstaking
    const stakingContract = contractService.getStakingVaultContract(true)
    if (!stakingContract) {
      throw new Error('Contract not available')
    }

    if (unstakeAmount.value == stakingStore.stakedAmount) {
      const withdrawTx = await stakingContract.redeem(
        parseUnits(stakingStore.stCINABalance, 18),
        walletStore.address,
        walletStore.address
      )
      currentTransactionStep.value = 2
      isQuickAmountModeOfUnstake.value = false
      const receipt = await withdrawTx.wait()

      currentTransactionStep.value = 3
      transactionStatus.value = 'success'
      transactionHash.value = receipt.hash
    } else {
      const withdrawTx = await stakingContract.withdraw(amountWei, walletStore.address, walletStore.address)
      currentTransactionStep.value = 2
      isQuickAmountModeOfUnstake.value = false
      const receipt = await withdrawTx.wait()

      currentTransactionStep.value = 3
      transactionStatus.value = 'success'
      transactionHash.value = receipt.hash
    }


    // Reset form and refresh data
    unstakeAmount.value = ''
    await stakingStore.fetchStakingData()
    ElMessage.success(t('staking.unstakeSuccess'))
  } catch (error: any) {
    transactionStatus.value = 'error'
    transactionError.value = error.message || t('staking.unstakeFailed')
    console.error('Unstake failed:', error)
  }
}

// Pull to refresh functionality
const refreshData = async () => {
  if (walletStore.isConnected) {
    await stakingStore.fetchStakingData()
  }
}

const { isRefreshing, pullDistance, isPulling, canRefresh } = usePullToRefresh({
  onRefresh: refreshData,
  enabled: true
})

// Lifecycle
onMounted(async () => {
  if (walletStore.isConnected) {
    await stakingStore.fetchStakingData()
    await stakingStore.startAutoRefresh()
  }
})

watch(
  () => stakingStore.cinaBalance,
  (newBalance) => {
    if (isQuickAmountModeOfStake.value) {
      stakeAmount.value = newBalance
      debouncedStakePreview(newBalance)
    }
  }
)

watch(
  () => stakingStore.stakedAmount,
  (newValue) => {
    if (isQuickAmountModeOfUnstake.value) {
      unstakeAmount.value = newValue
      debouncedUnstakePreview(newValue)
    }
  }
)

// Watch for wallet connection changes
watch(
  () => walletStore.isConnected,
  async (connected) => {
    if (connected) {
      await stakingStore.fetchStakingData()
      await stakingStore.startAutoRefresh();
    }
  }
)

// Watch for tab changes and reset input fields
watch(activeTab, (newTab) => {
  // Reset input amounts when switching tabs
  stakeAmount.value = ''
  stakePreviewData.value.shares = ''
  unstakeAmount.value = ''
  unstakePreviewData.value.shares = ''
})

const handleTransactionModalClose = () => {
  showTransactionModal.value = false
  transactionHash.value = ''
  transactionError.value = ''
}

const handleTransactionRetry = () => {
  if (activeTab.value === 'stake') {
    handleStake()
  } else {
    handleUnstake()
  }
}
</script>

<style scoped>
.section-title {
  @apply text-2xl font-bold mb-6;
  color: var(--text-primary);
}

.overview-grid {
  @apply grid grid-cols-1 gap-6 mb-8;
}

.overview-card {
  @apply rounded-xl p-6;
  background-color: var(--card-bg);
}

.card-header {
  @apply flex items-center justify-between mb-4;
}

.card-title {
  @apply text-sm font-medium;
  color: var(--text-secondary);
}

.card-icon {
  @apply text-xl;
  color: var(--primary-color);
}

.card-value {
  @apply text-2xl font-bold mb-2 flex items-center gap-2;
  color: var(--number-color);
}

.token-icon {
  @apply w-8 h-8 rounded-full object-cover;
}

.animated-number {
  @apply flex items-center;
}

.token-symbol {
  @apply text-lg font-medium;
  color: var(--text-secondary);
}

.card-subtitle {
  @apply text-sm font-medium;
  color: var(--text-secondary);
}

.action-section {
  @apply rounded-xl mb-8;
  background-color: var(--card-bg);
}

.staking-tabs {
  @apply p-6;
}

.tab-content {
  @apply mt-6;
}

.action-form {
  @apply space-y-6;
}

.input-section {
  @apply space-y-4;
}

.input-group {
  @apply space-y-2;
}

.amount-input {
  @apply w-full;
}

.input-suffix {
  @apply font-medium;
  color: var(--text-secondary);
}

.quick-amounts {
  @apply flex space-x-2;
}

.max-button {
  @apply hover:opacity-80;
  color: var(--primary-color);
}

.balance-info {
  @apply flex justify-between items-center text-sm;
}

.balance-label {
  color: var(--text-secondary);
}

.balance-value {
  @apply font-medium;
  color: var(--text-primary);
}

.warning-info {
  @apply flex items-center gap-2 p-3 rounded-lg text-sm;
  background-color: color-mix(in oklab, var(--warning-color) 15%, transparent);
  border: 1px solid color-mix(in oklab, var(--warning-color) 30%, var(--border-color));
  color: var(--warning-color);
}

.warning-info.early-unstake {
  background-color: color-mix(in oklab, var(--error-color) 15%, transparent);
  border-color: color-mix(in oklab, var(--error-color) 30%, var(--border-color));
  color: var(--error-color);
}

.preview-section {
  @apply rounded-lg p-4;
  background-color: var(--bg-secondary);
}

.preview-title {
  @apply text-sm font-medium mb-3;
  color: var(--text-primary);
}

.preview-details {
  @apply space-y-2;
}

.preview-row {
  @apply flex justify-between items-center text-sm;
}

.preview-row span:first-child {
  color: var(--text-secondary);
}

.preview-value {
  @apply font-medium;
  color: var(--text-primary);
}

.preview-row.penalty .preview-value {
  color: var(--error-color);
}

.exchange-rate {
  @apply pt-2 border-t;
  border-color: var(--border-color);
}

.preview-row.exchange-rate .preview-value {
  @apply font-semibold;
  color: var(--accent-color);
}

.action-button {
  @apply w-full h-12 text-base font-medium;
}

:deep(.el-tabs__header) {
  @apply mb-0;
}

:deep(.el-tabs__nav-wrap::after) {
  background-color: var(--border-color);
}

:deep(.el-tabs__active-bar) {
  background-color: var(--primary-color);
}

:deep(.el-tabs__item) {
  color: var(--text-secondary);
}

:deep(.el-tabs__item.is-active) {
  color: var(--primary-color);
}

@media (max-width: 768px) {
  .overview-grid {
    @apply grid-cols-1 gap-4;
  }
}
</style>

// src/pages/Staking.tsx
import { InfoCircleOutlined, QuestionCircleOutlined, WarningOutlined } from '@ant-design/icons'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ethers, formatUnits, parseUnits } from 'ethers'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { AnimatedNumber } from '@/components/common/AnimatedNumber'
import { FormattedInput } from '@/components/common/FormattedInput'
import { InfoCards } from '@/components/common/InfoCards'
import { PullToRefresh } from '@/components/common/PullToRefresh'
import { QuickAmounts } from '@/components/common/QuickAmounts'
import { TokenIcon } from '@/components/common/TokenIcon'
import { TransactionModal, type TransactionDetail, type TransactionStep } from '@/components/common/TransactionModal'
import { DEFAULT_CHAIN_ID } from '@/constants'
import {
  ORIGINAL_STAKING_BALANCES,
  ORIGINAL_STAKING_OVERVIEW,
  USE_LOCAL_DEMO_DATA
} from '@/data/originalDemoData'
import { useDebouncedValue } from '@/hooks/useDebouncedValue'
import { feedback } from '@/lib/feedback'
import { PageScaffold, PageSection } from '@/pages/PageScaffold'
import { contractService } from '@/services/contracts'
import { useStakingStore } from '@/stores/staking'
import { useWalletStore } from '@/stores/wallet'
import { calculatePercentageAmount, formatNumber, formatNumberK } from '@/utils/format'
import { resolveText } from '@/utils/i18n'

interface StakingView {
  yourStaked: string
  totalSupply: string
  cinaBalance: string
  stCINABalance: string
  stakedAmount: string
  currentAPY: string
  minStakeAmount: string
  navCina: string
  totalPendingAmount: string
}

interface PreviewResult {
  shares: string
  fee: string
}

const emptyStakingView: StakingView = {
  yourStaked: '0',
  totalSupply: '0',
  cinaBalance: '0',
  stCINABalance: '0',
  stakedAmount: '0',
  currentAPY: '0',
  minStakeAmount: '0',
  navCina: '1',
  totalPendingAmount: '0'
}

const emptyPreview: PreviewResult = {
  shares: '',
  fee: '0'
}

function getDemoStakingView(address: string): StakingView {
  return {
    cinaBalance: address ? ORIGINAL_STAKING_BALANCES.cinaBalance : '0',
    currentAPY: ORIGINAL_STAKING_OVERVIEW.currentAPY,
    minStakeAmount: ORIGINAL_STAKING_OVERVIEW.minStakeAmount,
    navCina: ORIGINAL_STAKING_OVERVIEW.navCina,
    stCINABalance: address ? ORIGINAL_STAKING_BALANCES.stCINABalance : ORIGINAL_STAKING_OVERVIEW.stCINABalance,
    stakedAmount: address ? ORIGINAL_STAKING_BALANCES.stakedAmount : ORIGINAL_STAKING_OVERVIEW.stakedAmount,
    totalPendingAmount: ORIGINAL_STAKING_OVERVIEW.totalPendingAmount,
    totalSupply: ORIGINAL_STAKING_OVERVIEW.totalSupply,
    yourStaked: ORIGINAL_STAKING_OVERVIEW.yourStaked
  }
}

export default function StakingPage() {
  const { t } = useTranslation()
  const wallet = useWalletStore()
  const queryClient = useQueryClient()
  const activeTab = useStakingStore(state => state.activeTab)
  const setActiveTab = useStakingStore(state => state.setActiveTab)
  const chainId = wallet.chainId || DEFAULT_CHAIN_ID

  const [stakeAmount, setStakeAmount] = useState('')
  const [unstakeAmount, setUnstakeAmount] = useState('')
  const [transactionVisible, setTransactionVisible] = useState(false)
  const [transactionTitle, setTransactionTitle] = useState('')
  const [transactionHash, setTransactionHash] = useState('')
  const [transactionError, setTransactionError] = useState('')
  const [transactionStatus, setTransactionStatus] = useState<'pending' | 'loading' | 'success' | 'error'>('pending')
  const [transactionStep, setTransactionStep] = useState(0)
  const debouncedStakeAmount = useDebouncedValue(stakeAmount)
  const debouncedUnstakeAmount = useDebouncedValue(unstakeAmount)

  const infoCards = useMemo(
    () => [
      {
        icon: <InfoCircleOutlined />,
        title: t('staking.whatIsStaking'),
        content: t('staking.stakingDescription')
      },
      {
        icon: <QuestionCircleOutlined />,
        title: t('staking.stakingRewards'),
        content: t('staking.stakingRewardsDescription')
      },
      {
        icon: <WarningOutlined />,
        title: t('staking.stakingRisks'),
        content: t('staking.stakingRisksDescription')
      }
    ],
    [t]
  )

  const transactionSteps: TransactionStep[] = useMemo(
    () => [
      { label: t('transaction.approve'), description: t('transaction.approveDescription') },
      { label: t('transaction.confirm'), description: t('transaction.confirmDescription') },
      { label: t('transaction.complete'), description: t('transaction.completeDescription') }
    ],
    [t]
  )

  const stakingQuery = useQuery({
    queryKey: ['staking', 'overview', chainId, wallet.address],
    refetchInterval: wallet.isConnected ? 6_000 : 30_000,
    queryFn: async (): Promise<StakingView> => {
      const stakingContract = contractService.getStakingVaultContract()
      const cinaContract = contractService.getCINAContract()
      if (!stakingContract) {
        return USE_LOCAL_DEMO_DATA ? getDemoStakingView(wallet.address) : emptyStakingView
      }

      const [totalSupply, navCina, minStakeAmount, maxWithdraw, lastDayRewardAmount, totalPendingAmount] =
        await Promise.all([
          stakingContract.totalSupply().catch(() => 0n),
          stakingContract.getNAV_CINA().catch(() => 1n),
          stakingContract.minStakeAmount().catch(() => 0n),
          wallet.address ? stakingContract.maxWithdraw(wallet.address).catch(() => 0n) : 0n,
          stakingContract.lastDayRewardAmount().catch(() => 0n),
          stakingContract.getTotalPendingAmount().catch(() => 0n)
        ])

      const totalSupplyValue = formatUnits(totalSupply, 18)
      const currentApy =
        Number.parseFloat(totalSupplyValue) > 0
          ? (
              (Number.parseFloat(formatUnits(lastDayRewardAmount, 18)) / Number.parseFloat(totalSupplyValue)) *
              365 *
              100
            ).toFixed(2)
          : '0'

      if (!wallet.address || !cinaContract) {
        return {
          ...emptyStakingView,
          currentAPY: currentApy,
          minStakeAmount: formatUnits(minStakeAmount, 18),
          navCina: formatUnits(navCina, 18),
          totalPendingAmount: formatUnits(totalPendingAmount, 18),
          totalSupply: totalSupplyValue,
          yourStaked: formatUnits(maxWithdraw, 18)
        }
      }

      const [cinaBalance, stCINABalance] = await Promise.all([
        cinaContract.balanceOf(wallet.address).catch(() => 0n),
        stakingContract.balanceOf(wallet.address).catch(() => 0n)
      ])

      return {
        cinaBalance: formatUnits(cinaBalance, 18),
        currentAPY: currentApy,
        minStakeAmount: formatUnits(minStakeAmount, 18),
        navCina: formatUnits(navCina, 18),
        stCINABalance: formatUnits(stCINABalance, 18),
        stakedAmount: formatUnits(maxWithdraw, 18),
        totalPendingAmount: formatUnits(totalPendingAmount, 18),
        totalSupply: totalSupplyValue,
        yourStaked: formatUnits(maxWithdraw, 18)
      }
    }
  })

  const stakingView = stakingQuery.data ?? emptyStakingView

  const stakePreviewQuery = useQuery({
    enabled: Number.parseFloat(debouncedStakeAmount) > 0,
    queryKey: ['staking', 'preview', 'stake', chainId, debouncedStakeAmount],
    queryFn: async (): Promise<PreviewResult> => {
      const stakingContract = contractService.getStakingVaultContract()
      if (!stakingContract) {
        return emptyPreview
      }

      const shares = await stakingContract.previewDeposit(parseUnits(debouncedStakeAmount, 18))
      return {
        shares: formatUnits(shares, 18),
        fee: '0'
      }
    }
  })

  const unstakePreviewQuery = useQuery({
    enabled: Number.parseFloat(debouncedUnstakeAmount) > 0,
    queryKey: ['staking', 'preview', 'unstake', chainId, debouncedUnstakeAmount],
    queryFn: async (): Promise<PreviewResult> => {
      const stakingContract = contractService.getStakingVaultContract()
      if (!stakingContract) {
        return emptyPreview
      }

      const shares = await stakingContract.previewWithdraw(parseUnits(debouncedUnstakeAmount, 18))
      return {
        shares: formatUnits(shares, 18),
        fee: '0'
      }
    }
  })

  const stakePreview = stakePreviewQuery.data ?? emptyPreview
  const unstakePreview = unstakePreviewQuery.data ?? emptyPreview

  const isStakeValid =
    Number.parseFloat(stakeAmount) > 0 &&
    Number.parseFloat(stakeAmount) <= Number.parseFloat(stakingView.cinaBalance) &&
    Number.parseFloat(stakeAmount) >= Number.parseFloat(stakingView.minStakeAmount)
  const isUnstakeValid =
    Number.parseFloat(unstakeAmount) > 0 &&
    Number.parseFloat(unstakeAmount) <= Number.parseFloat(stakingView.stakedAmount)
  const showMinStakeWarning =
    Number.parseFloat(stakeAmount) > 0 &&
    Number.parseFloat(stakeAmount) < Number.parseFloat(stakingView.minStakeAmount)

  const transactionDetails = useMemo<TransactionDetail[]>(() => {
    if (activeTab === 'stake' && stakeAmount) {
      return [
        {
          label: t('pay'),
          values: [`-${formatNumber(stakeAmount, 6)} CINA`],
          highlight: true,
          type: 'debit'
        },
        {
          label: t('receive'),
          values: [`+${formatNumber(stakePreview.shares || '0', 6)} stCINA`],
          type: 'credit'
        }
      ]
    }

    if (activeTab === 'unstake' && unstakeAmount) {
      return [
        {
          label: t('pay'),
          values: [`-${formatNumber(unstakePreview.shares || '0', 6)} stCINA`],
          type: 'debit'
        },
        {
          label: t('receive'),
          values: [`+${formatNumber(unstakeAmount, 6)} CINA`],
          highlight: true,
          type: 'credit'
        }
      ]
    }

    return []
  }, [activeTab, stakeAmount, stakePreview.shares, t, unstakeAmount, unstakePreview.shares])

  const refreshData = async () => {
    await queryClient.invalidateQueries({ queryKey: ['staking'] })
  }

  const resetTransaction = () => {
    setTransactionVisible(false)
    setTransactionHash('')
    setTransactionError('')
    setTransactionStatus('pending')
    setTransactionStep(0)
  }

  const handleStake = async () => {
    if (!wallet.isConnected || !wallet.address || !isStakeValid) {
      return
    }

    const stakingContract = contractService.getStakingVaultContract(true)
    const cinaContract = contractService.getCINAContract(true)
    if (!stakingContract || !cinaContract) {
      feedback.error(t('staking.stakeFailed'))
      return
    }

    setTransactionVisible(true)
    setTransactionTitle(t('staking.stakeTransaction'))
    setTransactionStatus('pending')
    setTransactionStep(0)

    try {
      const amountWei = parseUnits(stakeAmount, 18)
      const stakingAddress = await stakingContract.getAddress()
      const allowance = await cinaContract.allowance(wallet.address, stakingAddress)
      if (allowance < amountWei) {
        setTransactionStatus('loading')
        const approveTx = await cinaContract.approve(stakingAddress, ethers.MaxUint256)
        await approveTx.wait()
      }

      setTransactionStep(1)
      setTransactionStatus('loading')
      const depositTx = await stakingContract.deposit(amountWei, wallet.address)
      const receipt = await depositTx.wait()

      setTransactionStep(2)
      setTransactionStatus('success')
      setTransactionHash(receipt.hash)
      setStakeAmount('')
      await refreshData()
      feedback.success(t('staking.stakeSuccess'))
    } catch (error) {
      setTransactionStatus('error')
      setTransactionError(error instanceof Error ? error.message : t('staking.stakeFailed'))
    }
  }

  const handleUnstake = async () => {
    if (!wallet.isConnected || !wallet.address || !isUnstakeValid) {
      return
    }

    const stakingContract = contractService.getStakingVaultContract(true)
    if (!stakingContract) {
      feedback.error(t('staking.unstakeFailed'))
      return
    }

    setTransactionVisible(true)
    setTransactionTitle(t('staking.unstakeTransaction'))
    setTransactionStatus('loading')
    setTransactionStep(0)

    try {
      const amountWei = parseUnits(unstakeAmount, 18)
      const transaction =
        unstakeAmount === stakingView.stakedAmount
          ? await stakingContract.redeem(parseUnits(stakingView.stCINABalance, 18), wallet.address, wallet.address)
          : await stakingContract.withdraw(amountWei, wallet.address, wallet.address)

      setTransactionStep(1)
      const receipt = await transaction.wait()
      setTransactionStep(2)
      setTransactionStatus('success')
      setTransactionHash(receipt.hash)
      setUnstakeAmount('')
      await refreshData()
      feedback.success(t('staking.unstakeSuccess'))
    } catch (error) {
      setTransactionStatus('error')
      setTransactionError(error instanceof Error ? error.message : t('staking.unstakeFailed'))
    }
  }

  const pageTitle = resolveText(t('navigation.staking'), 'navigation.staking', 'Staking')
  const overviewTitle = resolveText(t('staking.overview'), 'staking.overview', 'Overview')
  const connectWalletLabel = resolveText(t('wallet.connectWallet'), 'wallet.connectWallet', 'Connect Wallet')
  const stakeLabel = resolveText(t('staking.stakeCINA'), 'staking.stakeCINA', 'Stake CINA')
  const unstakeLabel = resolveText(t('staking.unstakeCINA'), 'staking.unstakeCINA', 'Unstake CINA')
  const previewLabel = resolveText(t('staking.preview'), 'staking.preview', 'Preview')
  const yourStakedLabel = resolveText(t('staking.yourStaked'), 'staking.yourStaked', 'Your Staked')
  const apyLabel = resolveText(t('staking.apy'), 'staking.apy', 'APY')
  const balanceLabel = resolveText(t('wrap.balance'), 'wrap.balance', 'Balance')

  return (
    <PageScaffold title={pageTitle}>
      <PullToRefresh isRefreshing={stakingQuery.isRefetching}>
        {!wallet.isConnected ? <div className="app-inline-note is-info mb-6">{connectWalletLabel}</div> : null}

        <PageSection>
          <div className="mb-6">
            <h2 className="page-section-title">{overviewTitle}</h2>
          </div>

          <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-6">
            <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="text-sm font-semibold text-[var(--text-secondary)]">{yourStakedLabel}</div>
                <div className="mt-2 text-sm text-[var(--text-secondary)]">
                  {apyLabel} {formatNumber(stakingView.currentAPY, 2)}%
                </div>
              </div>
              <div className="rounded-full bg-[var(--card-bg)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.08em] text-[var(--text-secondary)]">
                stCINA Vault
              </div>
            </div>

            <div className="mt-6 flex items-center gap-3 text-3xl font-bold text-[var(--number-color)]">
              <TokenIcon size="large" symbol="CINA" />
              <AnimatedNumber decimals={4} value={stakingView.yourStaked} />
            </div>
          </div>
        </PageSection>

        <PageSection>
          <div className="mb-8 flex items-center justify-center rounded-2xl bg-[var(--bg-secondary)] p-1">
            <button
              className={`w-full rounded-xl px-4 py-3 text-sm font-semibold transition ${
                activeTab === 'stake' ? 'bg-[var(--primary-color)] text-white' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
              type="button"
              onClick={() => {
                setActiveTab('stake')
                setStakeAmount('')
                setUnstakeAmount('')
              }}
            >
              {stakeLabel}
            </button>
            <button
              className={`w-full rounded-xl px-4 py-3 text-sm font-semibold transition ${
                activeTab === 'unstake'
                  ? 'bg-[var(--primary-color)] text-white'
                  : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
              }`}
              type="button"
              onClick={() => {
                setActiveTab('unstake')
                setStakeAmount('')
                setUnstakeAmount('')
              }}
            >
              {unstakeLabel}
            </button>
          </div>

          {activeTab === 'stake' ? (
            <div className="space-y-6">
              <div>
                <div className="mb-3 flex items-center justify-between gap-4 text-sm">
                  <span className="font-medium text-[var(--text-primary)]">{stakeLabel}</span>
                  <span className="text-[var(--text-secondary)]">
                    {balanceLabel}: {formatNumberK(stakingView.cinaBalance)} CINA
                  </span>
                </div>
                <FormattedInput
                  className="w-full"
                  decimals={6}
                  maxDecimals={18}
                  modelValue={stakeAmount}
                  placeholder={`${formatNumberK(stakingView.cinaBalance)} ${t('available')}`}
                  size="large"
                  useAbbreviation
                  onChange={setStakeAmount}
                >
                  <span className="flex items-center gap-2">
                    <TokenIcon size="medium" symbol="CINA" />
                    <span>CINA</span>
                  </span>
                </FormattedInput>
                <div className="mt-4">
                  <QuickAmounts
                    maxLabel={t('common.max')}
                    onSelectMax={() => setStakeAmount(stakingView.cinaBalance)}
                    onSelectPercentage={percentage =>
                      setStakeAmount(calculatePercentageAmount(stakingView.cinaBalance, percentage))
                    }
                  />
                </div>
              </div>

              {showMinStakeWarning ? (
                <div className="app-inline-note is-warning">
                  {t('staking.minStakeWarning', { amount: stakingView.minStakeAmount })}
                </div>
              ) : null}

              {stakePreview.shares ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
                  <h3 className="text-base font-semibold text-[var(--text-primary)]">{previewLabel}</h3>
                  <div className="mt-4 space-y-3 text-sm">
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('staking.youWillReceive'), 'staking.youWillReceive', 'You Will Receive')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(stakePreview.shares, 2)} stCINA</span>
                    </div>
                    <div className="flex items-center justify-between gap-4 border-t border-[var(--border-color)] pt-3">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('staking.exchangeRate'), 'staking.exchangeRate', 'Exchange Rate')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">
                        1 CINA to {formatNumber(1 / Number.parseFloat(stakingView.navCina || '1'), 6)} stCINA
                      </span>
                    </div>
                  </div>
                </div>
              ) : null}

              <button
                className="app-action-button is-primary w-full"
                disabled={!isStakeValid || !wallet.isConnected}
                type="button"
                onClick={() => void handleStake()}
              >
                {wallet.isConnected ? stakeLabel : connectWalletLabel}
              </button>
            </div>
          ) : (
            <div className="space-y-6">
              <div>
                <div className="mb-3 flex items-center justify-between gap-4 text-sm">
                  <span className="font-medium text-[var(--text-primary)]">{unstakeLabel}</span>
                  <span className="text-[var(--text-secondary)]">
                    {balanceLabel}: {formatNumberK(stakingView.stakedAmount)} CINA
                  </span>
                </div>
                <FormattedInput
                  className="w-full"
                  decimals={6}
                  maxDecimals={18}
                  modelValue={unstakeAmount}
                  placeholder={`${formatNumberK(stakingView.stakedAmount)} ${t('available')}`}
                  size="large"
                  useAbbreviation
                  onChange={setUnstakeAmount}
                >
                  <span className="flex items-center gap-2">
                    <TokenIcon size="medium" symbol="CINA" />
                    <span>CINA</span>
                  </span>
                </FormattedInput>
                <div className="mt-4">
                  <QuickAmounts
                    maxLabel={t('common.max')}
                    onSelectMax={() => setUnstakeAmount(stakingView.stakedAmount)}
                    onSelectPercentage={percentage =>
                      setUnstakeAmount(calculatePercentageAmount(stakingView.stakedAmount, percentage))
                    }
                  />
                </div>
              </div>

              {unstakePreview.shares ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
                  <h3 className="text-base font-semibold text-[var(--text-primary)]">{previewLabel}</h3>
                  <div className="mt-4 space-y-3 text-sm">
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('staking.required'), 'staking.required', 'Required')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">{formatNumber(unstakePreview.shares, 2)} stCINA</span>
                    </div>
                    <div className="flex items-center justify-between gap-4 border-t border-[var(--border-color)] pt-3">
                      <span className="text-[var(--text-secondary)]">
                        {resolveText(t('staking.exchangeRate'), 'staking.exchangeRate', 'Exchange Rate')}
                      </span>
                      <span className="font-medium text-[var(--text-primary)]">
                        1 stCINA to {formatNumber(stakingView.navCina, 6)} CINA
                      </span>
                    </div>
                  </div>
                </div>
              ) : null}

              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-4">
                  <div className="text-sm text-[var(--text-secondary)]">
                    {resolveText(t('staking.stakedBalance'), 'staking.stakedBalance', 'Staked Balance')}
                  </div>
                  <div className="mt-2 font-semibold text-[var(--text-primary)]">{formatNumberK(stakingView.stCINABalance)} stCINA</div>
                </div>
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-4">
                  <div className="text-sm text-[var(--text-secondary)]">{apyLabel}</div>
                  <div className="mt-2 font-semibold text-[var(--text-primary)]">{formatNumber(stakingView.currentAPY, 2)}%</div>
                </div>
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-4">
                  <div className="text-sm text-[var(--text-secondary)]">
                    {resolveText(t('dashboard.todaysRemaining'), 'dashboard.todaysRemaining', "Today's Remaining")}
                  </div>
                  <div className="mt-2 font-semibold text-[var(--text-primary)]">{formatNumberK(stakingView.totalPendingAmount)} CINA</div>
                </div>
              </div>

              <button
                className="app-action-button is-primary w-full"
                disabled={!isUnstakeValid || !wallet.isConnected}
                type="button"
                onClick={() => void handleUnstake()}
              >
                {wallet.isConnected ? unstakeLabel : connectWalletLabel}
              </button>
            </div>
          )}
        </PageSection>

        <InfoCards cards={infoCards} />
      </PullToRefresh>

      <TransactionModal
        currentStep={transactionStep}
        errorMessage={transactionError}
        status={transactionStatus}
        steps={transactionSteps}
        title={transactionTitle}
        transactionDetails={transactionDetails}
        transactionHash={transactionHash}
        visible={transactionVisible}
        onClose={resetTransaction}
        onRetry={() => {
          if (activeTab === 'stake') {
            void handleStake()
          } else {
            void handleUnstake()
          }
        }}
      />
    </PageScaffold>
  )
}
