// src/views/Status.vue
<template>
  <div class="h-full">
    <PullToRefresh :is-pulling="isPulling" :is-refreshing="isRefreshing" :pull-distance="pullDistance"
      :can-refresh="canRefresh" class="h-full">
      <!-- Tokens Section -->
      <div class="mb-8">
        <h2 class="section-title">{{ t('status.tokenContracts') }}</h2>
        <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-2">
          <div v-for="(token, key) in TOKENS" :key="key" class="token-card">
            <div class="token-header">
              <h3 class="token-name">{{ token.name }}</h3>
              <span class="token-badge">{{ token.symbol }}</span>
            </div>
            <div class="token-details">
              <div class="detail-row">
                <span class="detail-label">{{ t('status.decimals') }}:</span>
                <span class="detail-value">{{ token.decimals }}</span>
              </div>

              <!-- Total Supply -->
              <div class="detail-row">
                <span class="detail-label">{{ t('status.totalSupply') }}:</span>
                <span v-if="tokenData[key]?.loading" class="loading-text">{{ t('common.loading') }}</span>
                <span v-else class="detail-value">
                  <el-tooltip :content="formatNumber(tokenData[key]?.totalSupply, token.decimals)" placement="top">
                    {{ formatLargeNumber(tokenData[key]?.totalSupply) }} {{ token.symbol }}
                  </el-tooltip>
                </span>
              </div>

              <!-- User Balance -->
              <div class="detail-row" v-if="walletStore.isConnected">
                <span class="detail-label">{{ t('status.myBalance') }}:</span>
                <span v-if="tokenData[key]?.loading" class="loading-text">{{ t('common.loading') }}</span>
                <span v-else class="balance-value">
                  <el-tooltip :content="formatNumber(tokenData[key]?.userBalance, token.decimals)" placement="top">
                    {{ formatLargeNumber(tokenData[key]?.userBalance) }} {{ token.symbol }}
                  </el-tooltip>
                </span>
              </div>

              <div class="detail-row">
                <span class="detail-label">{{ t('status.address') }}:</span>
                <div class="address-container">
                  <div class="address-actions" v-if="getTokenAddress(token, selectedNetwork)">
                    {{ formatAddress(getTokenAddress(token, selectedNetwork) || '') || t('status.notDeployed') }}
                    <button @click="copyToClipboard(getTokenAddress(token, selectedNetwork)!)"
                      class="action-icon copy-icon" :title="t('status.copyAddress')">
                      <el-icon>
                        <DocumentCopy />
                      </el-icon>
                    </button>
                    <button @click="openInExplorer(getTokenAddress(token, selectedNetwork)!)"
                      class="action-icon explorer-icon" :title="t('status.viewOnExplorer')">
                      <el-icon>
                        <Link />
                      </el-icon>
                    </button>
                  </div>
                </div>
              </div>

              <!-- Action Buttons -->
              <div class="token-actions" v-if="getTokenAddress(token, selectedNetwork)">
                <button @click="openTransferModal(key)" :disabled="!walletStore.isConnected"
                  class="action-button primary-button">
                  {{ t('status.quickTransfer') }}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Contracts Section -->
      <div class="mb-6">
        <h2 class="section-title">{{ t('status.smartContracts') }}</h2>
        <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-2">
          <div v-for="(contract, key) in CONTRACTS" :key="key" class="contract-card">
            <div class="contract-header">
              <h3 class="contract-name">{{ formatContractName(key) }}</h3>
              <span class="contract-badge">{{ t('status.contract') }}</span>
            </div>
            <div class="contract-details">
              <div class="detail-row">
                <span class="detail-label">{{ t('status.address') }}:</span>
                <div class="address-container">

                  <div class="address-actions" v-if="getContractAddress(contract, selectedNetwork)">
                    {{ formatAddress(getContractAddress(contract,
                      selectedNetwork) || '0x0000000000000000000000000000000000000000') || t('status.notDeployed') }}
                    <button @click="copyToClipboard(getContractAddress(contract, selectedNetwork)!)"
                      class="action-icon copy-icon" :title="t('status.copyAddress')">
                      <el-icon>
                        <DocumentCopy />
                      </el-icon>
                    </button>
                    <button @click="openInExplorer(getContractAddress(contract, selectedNetwork)!)"
                      class="action-icon explorer-icon" :title="t('status.viewOnExplorer')">
                      <el-icon>
                        <Link />
                      </el-icon>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <!-- Action Buttons -->
            <div class="contract-actions">
              <button @click="openQueryModal(key, false)" class="action-button secondary-button">
                {{ t('status.queryBalance') }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </PullToRefresh>

    <!-- Query Balance Modal -->
    <div v-if="showQueryModal" class="modal-overlay">
      <div class="modal-content">
        <h3 class="modal-title">{{ t('status.queryBalanceModal.title') }}</h3>
        <div class="modal-body">
          <div>
            <label class="input-label">{{ t('status.queryBalanceModal.walletAddress') }}</label>
            <input v-model="queryAddress" type="text" :placeholder="t('status.queryBalanceModal.placeholder')"
              class="modal-input" />
          </div>
          <div class="modal-actions">
            <button @click="queryAddressBalance" :disabled="!queryAddress || isQuerying"
              class="modal-button primary-button">
              {{ isQuerying ? t('status.queryBalanceModal.querying') : t('status.queryBalanceModal.query') }}
            </button>
            <button @click="showQueryModal = false" class="modal-button secondary-button">
              {{ t('status.queryBalanceModal.cancel') }}
            </button>
          </div>

          <!-- Query Results -->
          <div v-if="Object.keys(queryResults).length > 0" class="query-results">
            <h4 class="results-title">{{ t('status.queryBalanceModal.results') }}</h4>
            <div v-for="(balance, tokenKey) in queryResults" :key="tokenKey" class="result-item">
              <span class="result-label">{{ TOKENS[tokenKey as keyof typeof TOKENS].symbol }}</span>
              <span class="result-value">{{ balance }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Transfer Modal -->
    <div v-if="showTransferModal" class="modal-overlay">
      <div class="modal-content">
        <h3 class="modal-title">{{ t('status.transferModal.title') }} - {{ TOKENS[transferData.tokenKey as keyof typeof
          TOKENS]?.symbol }}</h3>
        <div class="modal-body">
          <div>
            <label class="input-label">{{ t('status.transferModal.receiverAddress') }}</label>
            <input v-model="transferData.toAddress" type="text"
              :placeholder="t('status.transferModal.receiverPlaceholder')" class="modal-input" />
          </div>
          <div>
            <label class="input-label">{{ t('status.transferModal.transferAmount') }}</label>
            <input v-model="transferData.amount" type="number" step="0.000001"
              :placeholder="t('status.transferModal.amountPlaceholder')" class="modal-input" />
            <div class="balance-hint">
              {{ t('status.transferModal.availableBalance') }}: {{ tokenData[transferData.tokenKey]?.userBalance }} {{
                TOKENS[transferData.tokenKey as keyof typeof TOKENS]?.symbol }}
            </div>
          </div>
          <div class="modal-actions">
            <button @click="executeTransfer"
              :disabled="!transferData.toAddress || !transferData.amount || transferData.loading"
              class="modal-button primary-button">
              {{ transferData.loading ? t('status.transferModal.transferring') :
                t('status.transferModal.confirmTransfer') }}
            </button>
            <button @click="showTransferModal = false" :disabled="transferData.loading"
              class="modal-button secondary-button">
              {{ t('status.transferModal.cancel') }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Toast Notification -->
    <div v-if="showToast" class="toast-notification">
      {{ toastMessage }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { NETWORKS, TOKENS, CONTRACTS } from '@/constants'
import { useWalletStore } from '@/stores/wallet'
import { contractService } from '@/services/contracts'
import { formatEther, formatUnits, parseUnits } from 'ethers'
import { formatLargeNumber, formatNumber, formatAddress } from '@/utils/format'
import PullToRefresh from '@/components/common/PullToRefresh.vue'
import { usePullToRefresh } from '@/composables/usePullToRefresh'
import { DocumentCopy, Link } from '@element-plus/icons-vue'

const { t } = useI18n()

const { isRefreshing, isPulling, pullDistance, canRefresh } = usePullToRefresh({
  onRefresh: async () => {
    await loadTokenData()
  },
})

const walletStore = useWalletStore()
const selectedNetwork = ref(walletStore.chainId || 1) // Default to current wallet network or Ethereum mainnet
const showToast = ref(false)
const toastMessage = ref(t('status.toast.addressCopied'))

// Token data state
const tokenData = ref<Record<string, {
  totalSupply: string
  userBalance: string
  loading: boolean
}>>({})

// Query functionality state
const queryAddress = ref('')
const queryResults = ref<Record<string, string>>({})
const isQuerying = ref(false)
const showQueryModal = ref(false)

// Transfer functionality state
const showTransferModal = ref(false)
const transferData = ref({
  tokenKey: '',
  toAddress: '',
  amount: '',
  loading: false
})

// Watch for wallet network changes
watch(
  () => walletStore.chainId,
  (newChainId) => {
    if (newChainId && newChainId !== selectedNetwork.value) {
      selectedNetwork.value = newChainId
      loadTokenData()
    }
  },
  { immediate: true }
)

const availableNetworks = computed(() => {
  return Object.values(NETWORKS).filter(network => network.chainId !== undefined)
})

const currentNetwork = computed(() => {
  return Object.values(NETWORKS).find(network => network.chainId === selectedNetwork.value)
})

const getTokenAddress = (token: any, chainId: number): string | null => {
  return token.addresses[chainId] || null
}

const getContractAddress = (contract: any, chainId: number, isToken = false): string | null => {
  if (isToken) {
    return contract.addresses[chainId] || null
  }
  return contract[chainId] || null
}

const formatContractName = (key: string): string => {
  return key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
}

const openInExplorer = (address: string) => {
  const network = currentNetwork.value
  if (network?.blockExplorer) {
    const url = `${network.blockExplorer}/address/${address}`
    window.open(url, '_blank')
  }
}

const showToastMessage = (message: string) => {
  toastMessage.value = message
  showToast.value = true
  setTimeout(() => {
    showToast.value = false
  }, 3000)
}

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    showToastMessage(t('status.toast.addressCopied'))
  } catch (err) {
    console.error('复制失败:', err)
  }
}

// Load token data (total supply and user balance)
const loadTokenData = async () => {
  if (!walletStore.provider) return

  for (const [key, token] of Object.entries(TOKENS)) {
    tokenData.value[key] = {
      totalSupply: '0',
      userBalance: '0',
      loading: true
    }

    try {
      const tokenAddress = getTokenAddress(token, selectedNetwork.value)
      if (!tokenAddress) continue

      const contract = contractService.getERC20Contract(tokenAddress)
      if (!contract) continue

      const [totalSupply, userBalance] = await Promise.all([
        contract.totalSupply(),
        walletStore.address ? contract.balanceOf(walletStore.address) : Promise.resolve(0)
      ])

      tokenData.value[key] = {
        totalSupply: formatUnits(totalSupply, token.decimals),
        userBalance: formatUnits(userBalance, token.decimals),
        loading: false
      }
    } catch (error) {
      console.error(`Failed to load data for ${key}:`, error)
      tokenData.value[key].loading = false
    }
  }
}

// Watch for wallet connection changes
watch(
  () => walletStore.isConnected,
  () => {
    loadTokenData()
  },
  { immediate: true }
)

// Watch for selected network changes
watch(
  selectedNetwork,
  () => {
    loadTokenData()
  }
)

// Query address balance
const queryAddressBalance = async () => {
  if (!queryAddress.value || !walletStore.provider) return

  isQuerying.value = true
  queryResults.value = {}

  try {
    for (const [key, token] of Object.entries(TOKENS)) {
      const tokenAddress = getTokenAddress(token, selectedNetwork.value)
      if (!tokenAddress) continue

      const contract = contractService.getERC20Contract(tokenAddress)
      if (!contract) continue

      const balance = await contract.balanceOf(queryAddress.value)
      queryResults.value[key] = formatEther(balance)
    }
  } catch (error) {
    console.error('Failed to query address balance:', error)
    toastMessage.value = t('status.balanceModal.queryFailed')
    showToast.value = true
    setTimeout(() => {
      showToast.value = false
    }, 2000)
  } finally {
    isQuerying.value = false
  }
}

const openQueryModal = (key: string, isToken = true) => {
  const token = isToken ? TOKENS[key as keyof typeof TOKENS] : CONTRACTS[key as keyof typeof CONTRACTS]
  queryAddress.value = getContractAddress(token, selectedNetwork.value, isToken) || ''
  queryResults.value = {}
  showQueryModal.value = true
  queryAddressBalance();
}

// Open transfer modal
const openTransferModal = (tokenKey: string) => {
  transferData.value = {
    tokenKey,
    toAddress: '',
    amount: '',
    loading: false
  }
  showTransferModal.value = true
}

// Execute transfer
const executeTransfer = async () => {
  if (!transferData.value.toAddress || !transferData.value.amount || !walletStore.signer) {
    return
  }

  transferData.value.loading = true

  try {
    const token = TOKENS[transferData.value.tokenKey as keyof typeof TOKENS]
    const tokenAddress = getTokenAddress(token, selectedNetwork.value)
    if (!tokenAddress) throw new Error('Token not deployed on this network')

    const contract = contractService.getERC20Contract(tokenAddress, true)
    if (!contract) throw new Error('Failed to get contract')

    const amount = String(transferData.value.amount);
    const tx = await contract.transfer(transferData.value.toAddress, parseUnits(amount, token.decimals))

    toastMessage.value = t('status.toast.transferSubmitted')
    showToast.value = true
    setTimeout(() => {
      showToast.value = false
    }, 3000)

    await tx.wait()

    toastMessage.value = t('status.toast.transferSuccess')
    showToast.value = true
    setTimeout(() => {
      showToast.value = false
    }, 2000)

    showTransferModal.value = false
    loadTokenData() // Refresh balances
  } catch (error: any) {
    console.error('Transfer failed:', error)
    toastMessage.value = `${t('status.toast.transferFailed')}: ${error.message || t('status.toast.unknownError')}`
    showToast.value = true
    setTimeout(() => {
      showToast.value = false
    }, 3000)
  } finally {
    transferData.value.loading = false
  }
}

// Initialize data on mount
onMounted(() => {
  loadTokenData()
})
</script>

<style scoped>
/* Status Page Styles */
.page-title {
  font-size: 1.875rem;
  font-weight: bold;
  color: var(--text-primary);
  margin-bottom: 2rem;
}

.section-title {
  font-size: 24px;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 24px;
}

.token-card,
.contract-card {
  background-color: var(--card-bg);
  border-radius: 0.75rem;
  padding: 1.5rem;
  transition: all 0.3s ease;
}

/* .token-card:hover,
.contract-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  transform: translateY(-2px);
} */

.token-header,
.contract-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 0.75rem;
}

.token-name,
.contract-name {
  font-size: 1.125rem;
  font-weight: 600;
  color: var(--text-primary);
}

.token-badge {
  padding: 0.25rem 0.5rem;
  background-color: var(--bg-secondary);
  color: var(--text-primary);
  font-size: 0.875rem;
  font-weight: 500;
  border-radius: 0.375rem;
}

.contract-badge {
  padding: 0.25rem 0.5rem;
  background-color: var(--success-color);
  color: white;
  font-size: 0.875rem;
  font-weight: 500;
  border-radius: 0.375rem;
}

.token-details,
.contract-details {
  margin-bottom: 1rem;
}

.detail-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.75rem;
  font-size: 0.875rem;
}

.detail-label {
  color: var(--text-secondary);
}

.detail-value {
  color: var(--text-secondary);
}

.loading-text {
  color: var(--text-secondary);
}

.balance-value {
  color: var(--text-secondary);
}

.address-container {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.address-actions {
  display: flex;
  align-items: center;
  gap: 0.65rem;
  color: var(--text-secondary);
}

.action-icon {
  display: flex;
  align-items: center;
  background: none;
  border: none;
  cursor: pointer;
  transition: all 0.2s ease;
}

.action-icon:hover {
  color: var(--primary-color);
}

.explorer-icon {
  color: var(--text-secondary);
}

.copy-icon {
  color: var(--text-secondary);
}

.token-actions,
.contract-actions {
  display: flex;
  gap: 0.5rem;
}

.action-button {
  flex: 1;
  padding: 0.5rem 0.75rem;
  font-size: 0.875rem;
  border-radius: 0.375rem;
  border: 1px solid var(--border-color);
  cursor: pointer;
  transition: all 0.2s ease;
}

.primary-button {
  background-color: var(--primary-color);
  border-color: var(--primary-color);
  color: var(--button-bg);
}

.primary-button:hover:not(:disabled) {
  background-color: var(--bg-primary);
  border-color: var(--button-primary-hover);
  color: var(--text-primary);
}

.secondary-button {
  background-color: var(--bg-secondary);
  border-color: var(--border-color);
  color: var(--text-secondary);
}

.secondary-button:hover:not(:disabled) {
  background-color: var(--bg-primary);
  color: var(--text-primary);
}

.action-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Modal Styles */
.modal-overlay {
  position: fixed;
  inset: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 50;
}

.modal-content {
  background-color: var(--card-bg);
  border-radius: 0.5rem;
  padding: 1.5rem;
  width: 100%;
  max-width: 28rem;
  margin: 1rem;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
}

.modal-title {
  font-size: 1.125rem;
  font-weight: 600;
  margin-bottom: 1rem;
  color: var(--text-primary);
}

.modal-body {
  margin-bottom: 1rem;
}

.input-label {
  display: block;
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--text-secondary);
  margin-bottom: 0.5rem;
}

.modal-input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 0.375rem;
  background-color: var(--card-bg);
  color: var(--text-primary);
  font-size: 0.875rem;
}

.modal-input:focus {
  outline: none;
  border-color: var(--primary-color);
  box-shadow: 0 0 0 1px var(--primary-color);
}

.modal-input::placeholder {
  color: var(--text-secondary);
}

.modal-actions {
  display: flex;
  gap: 0.75rem;
  margin-top: 1rem;
}

.modal-button {
  flex: 1;
  padding: 0.75rem 1rem;
  font-size: 0.875rem;
  font-weight: 500;
  border-radius: 0.375rem;
  border: none;
  cursor: pointer;
  transition: all 0.2s ease;
}

.balance-hint {
  margin-top: 0.25rem;
  font-size: 0.75rem;
  color: var(--text-secondary);
}

.query-results {
  margin-top: 1rem;
}

.results-title {
  font-weight: 500;
  color: var(--text-primary);
  margin-bottom: 0.5rem;
}

.result-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 0.75rem;
  background-color: var(--bg-secondary);
  border-radius: 0.375rem;
  margin-bottom: 0.25rem;
}

.result-label {
  font-weight: 500;
  color: var(--text-primary);
}

.result-value {
  font-size: 0.875rem;
  color: var(--text-secondary);
}

/* Toast Notification */
.toast-notification {
  position: fixed;
  top: 1rem;
  right: 1rem;
  background-color: var(--success-color);
  color: white;
  padding: 1rem 1.5rem;
  border-radius: 0.375rem;
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
  z-index: 50;
  transition: all 0.3s ease;
}

code {
  word-break: break-all;
  max-width: 200px;
  display: inline-block;
}

/* Dark mode transitions */
* {
  transition: background-color 0.3s ease, border-color 0.3s ease, color 0.3s ease;
}

/* Custom scrollbar for dark mode */
::-webkit-scrollbar {
  width: 8px;
}

::-webkit-scrollbar-track {
  @apply bg-gray-100 dark:bg-gray-800;
}

::-webkit-scrollbar-thumb {
  @apply bg-gray-300 dark:bg-gray-600 rounded;
}

::-webkit-scrollbar-thumb:hover {
  @apply bg-gray-400 dark:bg-gray-500;
}

@media (max-width: 768px) {
  code {
    max-width: 220px;
  }
}
</style>

// src/pages/Status.tsx
import { CopyOutlined, DownOutlined, LinkOutlined, ReloadOutlined } from '@ant-design/icons'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { formatUnits, parseUnits } from 'ethers'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { DEFAULT_CHAIN_ID, NETWORKS, TOKENS, CONTRACTS } from '@/constants'
import { feedback } from '@/lib/feedback'
import { PageScaffold, PageSection } from '@/pages/PageScaffold'
import { contractService } from '@/services/contracts'
import { useWalletStore } from '@/stores/wallet'
import { formatAddress, formatLargeNumber } from '@/utils/format'
import { resolveText } from '@/utils/i18n'

interface TokenView {
  totalSupply: string
  userBalance: string
  loading: boolean
}

const emptyTokenView: TokenView = {
  loading: false,
  totalSupply: '0',
  userBalance: '0'
}

export default function StatusPage() {
  const { t } = useTranslation()
  const wallet = useWalletStore()
  const queryClient = useQueryClient()
  const currentChainId = wallet.chainId || DEFAULT_CHAIN_ID

  const [selectedNetwork, setSelectedNetwork] = useState(currentChainId)
  const [networkMenuOpen, setNetworkMenuOpen] = useState(false)
  const [queryOpen, setQueryOpen] = useState(false)
  const [queryAddress, setQueryAddress] = useState('')
  const [queryLoading, setQueryLoading] = useState(false)
  const [queryResults, setQueryResults] = useState<Record<string, string>>({})
  const [transferOpen, setTransferOpen] = useState(false)
  const [transferTokenKey, setTransferTokenKey] = useState<keyof typeof TOKENS | ''>('')
  const [transferToAddress, setTransferToAddress] = useState('')
  const [transferAmount, setTransferAmount] = useState('')
  const [transferLoading, setTransferLoading] = useState(false)

  useEffect(() => {
    if (selectedNetwork === currentChainId) {
      setSelectedNetwork(currentChainId)
    }
  }, [currentChainId, selectedNetwork])

  const liveDataEnabled = selectedNetwork === currentChainId
  const tokenEntries = Object.entries(TOKENS)
  const contractEntries = Object.entries(CONTRACTS)
  const selectedNetworkConfig =
    Object.values(NETWORKS).find(network => network.chainId === selectedNetwork) ?? NETWORKS.ETHEREUM

  const tokenDataQuery = useQuery({
    queryKey: ['status', 'tokens', selectedNetwork, currentChainId, wallet.address],
    refetchInterval: liveDataEnabled ? 15_000 : false,
    queryFn: async (): Promise<Record<string, TokenView>> => {
      if (!liveDataEnabled) {
        return Object.fromEntries(tokenEntries.map(([key]) => [key, emptyTokenView]))
      }

      const results = await Promise.all(
        tokenEntries.map(async ([key, token]) => {
          const tokenAddress = token.addresses[selectedNetwork as keyof typeof token.addresses]
          if (!tokenAddress) {
            return [key, emptyTokenView] as const
          }

          const contract = contractService.getERC20Contract(tokenAddress)
          if (!contract) {
            return [key, emptyTokenView] as const
          }

          const [totalSupply, userBalance] = await Promise.all([
            contract.totalSupply().catch(() => 0n),
            wallet.address ? contract.balanceOf(wallet.address).catch(() => 0n) : 0n
          ])

          return [
            key,
            {
              loading: false,
              totalSupply: formatUnits(totalSupply, token.decimals),
              userBalance: formatUnits(userBalance, token.decimals)
            }
          ] as const
        })
      )

      return Object.fromEntries(results)
    }
  })

  const tokenData = tokenDataQuery.data ?? {}
  const networkOptions = useMemo(
    () =>
      Object.values(NETWORKS).map(network => ({
        label: network.name,
        value: network.chainId
      })),
    []
  )

  const handleCopy = async (value: string) => {
    try {
      await navigator.clipboard.writeText(value)
      feedback.success(t('status.toast.addressCopied'))
    } catch {
      feedback.error(t('status.toast.queryFailed'))
    }
  }

  const openExplorer = (address: string) => {
    if (!selectedNetworkConfig.blockExplorer) {
      return
    }

    window.open(`${selectedNetworkConfig.blockExplorer}/address/${address}`, '_blank', 'noopener,noreferrer')
  }

  const refreshData = async () => {
    await queryClient.invalidateQueries({ queryKey: ['status'] })
  }

  const openQueryModal = (initialAddress: string) => {
    setQueryAddress(initialAddress)
    setQueryResults({})
    setQueryOpen(true)
  }

  const queryAddressBalance = async () => {
    if (!queryAddress) {
      return
    }

    if (!liveDataEnabled) {
      feedback.warning(`${t('status.selectNetwork')}: ${selectedNetworkConfig.name}`)
      return
    }

    setQueryLoading(true)
    setQueryResults({})

    try {
      const results = await Promise.all(
        tokenEntries.map(async ([key, token]) => {
          const tokenAddress = token.addresses[selectedNetwork as keyof typeof token.addresses]
          if (!tokenAddress) {
            return [key, '0'] as const
          }

          const contract = contractService.getERC20Contract(tokenAddress)
          if (!contract) {
            return [key, '0'] as const
          }

          const balance = await contract.balanceOf(queryAddress).catch(() => 0n)
          return [key, formatUnits(balance, token.decimals)] as const
        })
      )

      setQueryResults(Object.fromEntries(results))
    } catch {
      feedback.error(t('status.toast.queryFailed'))
    } finally {
      setQueryLoading(false)
    }
  }

  const openTransferModal = (tokenKey: keyof typeof TOKENS) => {
    setTransferTokenKey(tokenKey)
    setTransferToAddress('')
    setTransferAmount('')
    setTransferOpen(true)
  }

  const executeTransfer = async () => {
    if (!transferTokenKey || !transferToAddress || !transferAmount) {
      return
    }

    if (!wallet.isConnected || !liveDataEnabled) {
      feedback.warning(t('wallet.connectWallet'))
      return
    }

    const token = TOKENS[transferTokenKey]
    const tokenAddress = token.addresses[selectedNetwork as keyof typeof token.addresses]
    const contract = tokenAddress ? contractService.getERC20Contract(tokenAddress, true) : null
    if (!contract) {
      feedback.error(t('status.toast.transferFailed'))
      return
    }

    setTransferLoading(true)

    try {
      feedback.info(t('status.toast.transferSubmitted'))
      const tx = await contract.transfer(transferToAddress, parseUnits(transferAmount, token.decimals))
      await tx.wait()
      feedback.success(t('status.toast.transferSuccess'))
      setTransferOpen(false)
      await refreshData()
    } catch (error) {
      feedback.error(error instanceof Error ? error.message : t('status.toast.transferFailed'))
    } finally {
      setTransferLoading(false)
    }
  }

  const pageTitle = resolveText(t('status.title'), 'status.title', 'Status')
  const connectWalletLabel = resolveText(t('wallet.connectWallet'), 'wallet.connectWallet', 'Connect Wallet')
  const tokenContractsTitle = resolveText(t('status.tokenContracts'), 'status.tokenContracts', 'Token Contracts')
  const smartContractsTitle = resolveText(t('status.smartContracts'), 'status.smartContracts', 'Smart Contracts')
  const myBalanceLabel = resolveText(t('status.myBalance'), 'status.myBalance', 'My Balance')
  const refreshLabel = resolveText(t('status.refresh'), 'status.refresh', 'Refresh')
  const selectNetworkLabel = resolveText(t('status.selectNetwork'), 'status.selectNetwork', 'Select Network')
  const queryBalanceLabel = resolveText(t('status.queryBalance'), 'status.queryBalance', 'Query Balance')
  const quickTransferLabel = resolveText(t('status.quickTransfer'), 'status.quickTransfer', 'Quick Transfer')
  const addressLabel = resolveText(t('status.address'), 'status.address', 'Address')
  const totalSupplyLabel = resolveText(t('status.totalSupply'), 'status.totalSupply', 'Total Supply')
  const decimalsLabel = resolveText(t('status.decimals'), 'status.decimals', 'Decimals')
  const notDeployedLabel = resolveText(t('status.notDeployed'), 'status.notDeployed', 'Not Deployed')
  const contractLabel = resolveText(t('status.contract'), 'status.contract', 'Contract')
  const transferTitle = resolveText(t('status.transferModal.title'), 'status.transferModal.title', 'Transfer Token')
  const transferConfirmLabel = resolveText(
    t('status.transferModal.confirmTransfer'),
    'status.transferModal.confirmTransfer',
    'Confirm Transfer'
  )
  const transferCancelLabel = resolveText(t('status.transferModal.cancel'), 'status.transferModal.cancel', 'Cancel')
  const transferReceiverLabel = resolveText(
    t('status.transferModal.receiverPlaceholder'),
    'status.transferModal.receiverPlaceholder',
    'Receiver Address'
  )
  const transferAmountLabel = resolveText(
    t('status.transferModal.amountPlaceholder'),
    'status.transferModal.amountPlaceholder',
    'Amount'
  )
  const availableBalanceLabel = resolveText(
    t('status.transferModal.availableBalance'),
    'status.transferModal.availableBalance',
    'Available Balance'
  )
  const queryTitle = resolveText(t('status.queryBalanceModal.title'), 'status.queryBalanceModal.title', 'Query Balance')
  const queryPlaceholder = resolveText(
    t('status.queryBalanceModal.placeholder'),
    'status.queryBalanceModal.placeholder',
    'Wallet Address'
  )
  const queryConfirmLabel = resolveText(t('status.queryBalanceModal.query'), 'status.queryBalanceModal.query', 'Query')
  const queryCancelLabel = resolveText(t('status.queryBalanceModal.cancel'), 'status.queryBalanceModal.cancel', 'Cancel')

  const networkToolbar = (
    <div className="flex flex-wrap items-center justify-end gap-3">
      <div className="relative">
        <button className="app-action-button is-subtle" type="button" onClick={() => setNetworkMenuOpen(open => !open)}>
          <span>{selectedNetworkConfig.name}</span>
          <DownOutlined />
        </button>
        {networkMenuOpen ? (
          <div className="app-dropdown-menu min-w-[15rem]">
            <div className="px-3 py-2 text-xs font-semibold uppercase tracking-[0.08em] text-[var(--text-secondary)]">
              {selectNetworkLabel}
            </div>
            {networkOptions.map(option => (
              <button
                key={option.value}
                className={`app-dropdown-item ${selectedNetwork === option.value ? 'text-[var(--primary-color)]' : ''}`}
                type="button"
                onClick={() => {
                  setSelectedNetwork(option.value)
                  setNetworkMenuOpen(false)
                }}
              >
                <span>{option.label}</span>
                {selectedNetwork === option.value ? <span>Current</span> : null}
              </button>
            ))}
          </div>
        ) : null}
      </div>
      <button className="app-action-button is-subtle" type="button" onClick={() => void refreshData()}>
        <ReloadOutlined />
        <span>{refreshLabel}</span>
      </button>
    </div>
  )

  return (
    <PageScaffold extra={networkToolbar} title={pageTitle}>
      {!liveDataEnabled ? (
        <div className="app-inline-note is-info mb-6">
          {selectNetworkLabel}: {selectedNetworkConfig.name}
        </div>
      ) : null}

      <div className="mb-8">
        <div className="mb-6">
          <h2 className="page-section-title">{tokenContractsTitle}</h2>
          <p className="mt-2 text-sm text-[var(--text-secondary)]">
            {wallet.isConnected ? myBalanceLabel : resolveText(t('wallet.connectWallet'), 'wallet.connectWallet', 'Connect Wallet')}
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          {tokenEntries.map(([key, token]) => {
            const rawTokenAddress = token.addresses[selectedNetwork as keyof typeof token.addresses] as string | undefined
            const tokenAddress = rawTokenAddress || '0x0000000000000000000000000000000000000000'
            const tokenView = tokenData[key] ?? emptyTokenView

            return (
              <article key={key} className="flex flex-col h-full rounded-2xl bg-[var(--card-bg)] border border-[var(--border-color)] p-6 relative">
                <div className="flex items-center justify-between mb-5">
                  <h3 className="text-xl font-bold text-[var(--text-primary)]">{token.name}</h3>
                  <span className="rounded-md bg-[var(--bg-secondary)] px-2 py-1 text-xs font-semibold uppercase tracking-wider text-[var(--text-secondary)]">
                    {token.symbol}
                  </span>
                </div>

                <div className="space-y-3 mb-6">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-[var(--text-secondary)]">{decimalsLabel}:</span>
                    <span className="font-medium text-[var(--text-primary)]">{token.decimals}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-[var(--text-secondary)]">{totalSupplyLabel}:</span>
                    <span className="font-medium text-[var(--text-primary)]">
                      {tokenAddress ? `${formatLargeNumber(tokenView.totalSupply)} ${token.symbol}` : notDeployedLabel}
                    </span>
                  </div>
                  {wallet.isConnected ? (
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[var(--text-secondary)]">{myBalanceLabel}:</span>
                      <span className="font-medium text-[var(--text-primary)]">
                        {`${formatLargeNumber(tokenView.userBalance)} ${token.symbol}`}
                      </span>
                    </div>
                  ) : null}
                  <div className="flex items-center justify-between text-sm pt-1">
                    <span className="text-[var(--text-secondary)]">{addressLabel}:</span>
                    {tokenAddress ? (
                      <div className="flex items-center gap-1">
                        <span className="text-[var(--text-secondary)]">{formatAddress(tokenAddress)}</span>
                        <button className="text-[var(--text-secondary)] hover:text-[var(--primary-color)] transition-colors p-1" type="button" onClick={() => void handleCopy(tokenAddress)} title={t('status.copyAddress')}>
                          <CopyOutlined />
                        </button>
                        <button className="text-[var(--text-secondary)] hover:text-[var(--primary-color)] transition-colors p-1" type="button" onClick={() => openExplorer(tokenAddress)} title={t('status.viewOnExplorer')}>
                          <LinkOutlined />
                        </button>
                      </div>
                    ) : (
                      <span className="text-[var(--text-secondary)]">{notDeployedLabel}</span>
                    )}
                  </div>
                </div>

                <div className="mt-auto">
                  <button
                    className="app-action-button w-full justify-center is-subtle mt-4"
                    style={{ backgroundColor: '#8a94b5', color: '#fff', border: 'none' }}
                    disabled={!tokenAddress || !wallet.isConnected || !liveDataEnabled}
                    type="button"
                    onClick={() => openTransferModal(key as keyof typeof TOKENS)}
                  >
                    {quickTransferLabel}
                  </button>
                </div>
              </article>
            )
          })}
        </div>
      </div>

      <div className="mb-8">
        <div className="mb-6">
          <h2 className="page-section-title">{smartContractsTitle}</h2>
          <p className="mt-2 text-sm text-[var(--text-secondary)]">{selectedNetworkConfig.name}</p>
        </div>

        {contractEntries.length === 0 ? (
          <div className="app-inline-note">{notDeployedLabel}</div>
        ) : (
          <div className="grid gap-4 md:grid-cols-2">
            {contractEntries.map(([key, contract]) => {
              const rawValue = contract[selectedNetwork as keyof typeof contract] as string | undefined
              const value = rawValue || '0x0000000000000000000000000000000000000000'
              return (
              <article key={key} className="flex flex-col h-full rounded-2xl bg-[var(--card-bg)] border border-[var(--border-color)] p-6 relative">
                <div className="flex items-center justify-between mb-5">
                  <h3 className="text-xl font-bold text-[var(--text-primary)]">{key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</h3>
                  <span className="rounded-md bg-[var(--success-color)] px-2 py-1 text-xs font-semibold uppercase tracking-wider text-white">
                    {contractLabel}
                  </span>
                </div>

                <div className="space-y-3 mb-6">
                  <div className="flex items-center justify-between text-sm pt-1">
                    <span className="text-[var(--text-secondary)]">{addressLabel}:</span>
                    {value ? (
                      <div className="flex items-center gap-1">
                        <span className="text-[var(--text-secondary)]">{formatAddress(value)}</span>
                        <button className="text-[var(--text-secondary)] hover:text-[var(--primary-color)] transition-colors p-1" type="button" onClick={() => void handleCopy(value)} title={t('status.copyAddress')}>
                          <CopyOutlined />
                        </button>
                        <button className="text-[var(--text-secondary)] hover:text-[var(--primary-color)] transition-colors p-1" type="button" onClick={() => openExplorer(value)} title={t('status.viewOnExplorer')}>
                          <LinkOutlined />
                        </button>
                      </div>
                    ) : (
                      <span className="text-[var(--text-secondary)]">{notDeployedLabel}</span>
                    )}
                  </div>
                </div>

                <div className="mt-auto">
                  <button
                    className="app-action-button w-full justify-center is-subtle mt-4"
                    disabled={!value}
                    type="button"
                    onClick={() => openQueryModal(value || '')}
                  >
                    {queryBalanceLabel}
                  </button>
                </div>
              </article>
            )})}
          </div>
        )}
      </div>

      {queryOpen ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(15,23,42,0.45)] p-4">
          <div className="w-full max-w-xl rounded-3xl border border-[var(--border-color)] bg-[var(--card-bg)] p-6 shadow-[0_24px_60px_rgba(15,23,42,0.18)]">
            <div className="mb-5 flex items-start justify-between gap-4">
              <div>
                <h2 className="text-xl font-bold text-[var(--text-primary)]">{queryTitle}</h2>
                <p className="mt-2 text-sm text-[var(--text-secondary)]">{queryPlaceholder}</p>
              </div>
              <button className="app-icon-button" type="button" onClick={() => setQueryOpen(false)}>
                ×
              </button>
            </div>

            <div className="space-y-5">
              <label className="block">
                <span className="mb-2 block text-sm font-medium text-[var(--text-primary)]">{addressLabel}</span>
                <input
                  className="w-full rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] px-4 py-3 text-[var(--text-primary)] outline-none"
                  placeholder={queryPlaceholder}
                  value={queryAddress}
                  onChange={event => setQueryAddress(event.target.value)}
                />
              </label>

              {Object.keys(queryResults).length > 0 ? (
                <div className="rounded-2xl bg-[var(--bg-secondary)] p-4">
                  <div className="space-y-3">
                    {Object.entries(queryResults).map(([key, value]) => (
                      <div key={key} className="flex items-center justify-between gap-4 text-sm">
                        <span className="text-[var(--text-secondary)]">{TOKENS[key as keyof typeof TOKENS].symbol}</span>
                        <span className="font-medium text-[var(--text-primary)]">{formatLargeNumber(value)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}

              <div className="flex flex-wrap justify-end gap-3">
                <button className="app-action-button is-subtle" type="button" onClick={() => setQueryOpen(false)}>
                  {queryCancelLabel}
                </button>
                <button
                  className="app-action-button is-primary"
                  disabled={queryLoading}
                  type="button"
                  onClick={() => void queryAddressBalance()}
                >
                  {queryLoading ? `${queryConfirmLabel}...` : queryConfirmLabel}
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {transferOpen ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(15,23,42,0.45)] p-4">
          <div className="w-full max-w-xl rounded-3xl border border-[var(--border-color)] bg-[var(--card-bg)] p-6 shadow-[0_24px_60px_rgba(15,23,42,0.18)]">
            <div className="mb-5 flex items-start justify-between gap-4">
              <div>
                <h2 className="text-xl font-bold text-[var(--text-primary)]">
                  {transferTitle}
                  {transferTokenKey ? ` - ${TOKENS[transferTokenKey].symbol}` : ''}
                </h2>
                <p className="mt-2 text-sm text-[var(--text-secondary)]">{selectedNetworkConfig.name}</p>
              </div>
              <button className="app-icon-button" type="button" onClick={() => setTransferOpen(false)}>
                ×
              </button>
            </div>

            <div className="space-y-5">
              <label className="block">
                <span className="mb-2 block text-sm font-medium text-[var(--text-primary)]">{transferReceiverLabel}</span>
                <input
                  className="w-full rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] px-4 py-3 text-[var(--text-primary)] outline-none"
                  placeholder={transferReceiverLabel}
                  value={transferToAddress}
                  onChange={event => setTransferToAddress(event.target.value)}
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-sm font-medium text-[var(--text-primary)]">{transferAmountLabel}</span>
                <input
                  className="w-full rounded-2xl border border-[var(--border-color)] bg-[var(--bg-secondary)] px-4 py-3 text-[var(--text-primary)] outline-none"
                  placeholder={transferAmountLabel}
                  value={transferAmount}
                  onChange={event => setTransferAmount(event.target.value)}
                />
                {transferTokenKey ? (
                  <div className="mt-2 text-sm text-[var(--text-secondary)]">
                    {availableBalanceLabel}: {formatLargeNumber(tokenData[transferTokenKey]?.userBalance || '0')} {TOKENS[transferTokenKey].symbol}
                  </div>
                ) : null}
              </label>

              <div className="flex flex-wrap justify-end gap-3">
                <button className="app-action-button is-subtle" disabled={transferLoading} type="button" onClick={() => setTransferOpen(false)}>
                  {transferCancelLabel}
                </button>
                <button
                  className="app-action-button is-primary"
                  disabled={!transferAmount || !transferToAddress || transferLoading}
                  type="button"
                  onClick={() => void executeTransfer()}
                >
                  {transferLoading ? `${transferConfirmLabel}...` : transferConfirmLabel}
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </PageScaffold>
  )
}
