// src/components/common/QuickAmounts.vue
<template>
  <div class="quick-amounts">
    <el-button class="btn-quick-amount" v-for="percentage in percentages" :key="percentage" link :size="size"
      @click="$emit('select-percentage', percentage)">
      {{ percentage }}%
    </el-button>
    <el-button class="btn-quick-amount" v-if="showMax" link :size="size" @click="$emit('select-max')">
      {{ maxLabel }}
    </el-button>
  </div>
</template>

<script setup lang="ts">
import { withDefaults, defineProps } from 'vue'

interface Props {
  percentages?: number[]
  showMax?: boolean
  maxLabel?: string
  size?: 'large' | 'default' | 'small'
}

withDefaults(defineProps<Props>(), {
  percentages: () => [25, 50, 75],
  showMax: true,
  maxLabel: 'MAX',
  size: 'small',
  type: 'text'
})
</script>

<style scoped>
.quick-amounts {
  display: flex;
  gap: 8px;
}

.btn-quick-amount {
  width: 42px;
}
</style>

// src/components/common/QuickAmounts.tsx
interface QuickAmountsProps {
  percentages?: number[]
  showMax?: boolean
  maxLabel?: string
  disabled?: boolean
  onSelectPercentage: (percentage: number) => void
  onSelectMax: () => void
}

export function QuickAmounts({
  disabled,
  maxLabel = 'MAX',
  onSelectMax,
  onSelectPercentage,
  percentages = [25, 50, 75],
  showMax = true
}: QuickAmountsProps) {
  return (
    <div className="quick-amounts">
      {percentages.map(percentage => (
        <button
          key={percentage}
          className="quick-amount-button"
          disabled={disabled}
          type="button"
          onClick={() => onSelectPercentage(percentage)}
        >
          {percentage}%
        </button>
      ))}
      {showMax ? (
        <button className="quick-amount-button" disabled={disabled} type="button" onClick={onSelectMax}>
          {maxLabel}
        </button>
      ) : null}
    </div>
  )
}
