// src/components/common/TransactionModal.tsx
import { CopyOutlined, LinkOutlined } from '@ant-design/icons'
import { SUPPORTED_NETWORKS, useWalletStore } from '@/stores/wallet'

export interface TransactionStep {
  label: string
  description?: string
}

export interface TransactionDetail {
  label: string
  values: string[]
  highlight?: boolean
  type?: 'debit' | 'credit'
}

interface GasInfo {
  gasLimit: string
  gasPrice: string
  estimatedFee: string
  maxFee: string
}

interface TransactionModalProps {
  visible: boolean
  title?: string
  steps: TransactionStep[]
  currentStep: number
  status: 'pending' | 'loading' | 'success' | 'error'
  transactionDetails: TransactionDetail[]
  gasInfo?: GasInfo
  transactionHash?: string
  errorMessage?: string
  showViewTransaction?: boolean
  onClose: () => void
  onRetry: () => void
}

function getStepState(index: number, currentStep: number, status: TransactionModalProps['status']) {
  if (status === 'error' && index === currentStep) {
    return 'error'
  }
  if (status === 'success' && index <= currentStep) {
    return 'done'
  }
  if (index < currentStep) {
    return 'done'
  }
  if (index === currentStep) {
    return status === 'error' ? 'error' : 'current'
  }
  return 'pending'
}

export function TransactionModal({
  currentStep,
  errorMessage,
  gasInfo,
  onClose,
  onRetry,
  showViewTransaction = true,
  status,
  steps,
  title,
  transactionDetails,
  transactionHash,
  visible
}: TransactionModalProps) {
  const chainId = useWalletStore(state => state.chainId)
  const blockExplorer = SUPPORTED_NETWORKS[chainId]?.blockExplorer
  const boundedStep = Math.min(currentStep, Math.max(steps.length - 1, 0))

  if (!visible) {
    return null
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(15,23,42,0.45)] p-4"
      onClick={event => {
        if (event.target === event.currentTarget && status !== 'loading') {
          onClose()
        }
      }}
    >
      <div className="w-full max-w-2xl rounded-3xl border border-[var(--border-color)] bg-[var(--card-bg)] p-6 shadow-[0_24px_60px_rgba(15,23,42,0.18)]">
        <div className="mb-5 flex items-start justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-[var(--text-primary)]">{title || 'Transaction'}</h2>
            <p className="mt-2 text-sm text-[var(--text-secondary)]">
              {status === 'success'
                ? 'Transaction complete.'
                : status === 'error'
                  ? 'Transaction failed.'
                  : 'Follow the steps below to complete your transaction.'}
            </p>
          </div>
          {status !== 'loading' ? (
            <button className="app-icon-button" type="button" onClick={onClose}>
              ×
            </button>
          ) : null}
        </div>

        <div className="space-y-6">
          <div className="grid gap-3 md:grid-cols-2">
            {steps.map((step, index) => {
              const state = getStepState(index, boundedStep, status)
              const isCurrent = state === 'current'
              const isDone = state === 'done'
              const isError = state === 'error'

              return (
                <div
                  key={`${step.label}-${index}`}
                  className={`rounded-2xl border px-4 py-4 ${
                    isError
                      ? 'border-[rgba(239,68,68,0.35)] bg-[rgba(239,68,68,0.08)]'
                      : isCurrent
                        ? 'border-[var(--primary-color)] bg-[var(--bg-secondary)]'
                        : isDone
                          ? 'border-[rgba(16,185,129,0.35)] bg-[rgba(16,185,129,0.08)]'
                          : 'border-[var(--border-color)] bg-[var(--bg-secondary)]'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <span
                      className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold ${
                        isError
                          ? 'bg-[var(--error-color)] text-white'
                          : isCurrent
                            ? 'bg-[var(--primary-color)] text-white'
                            : isDone
                              ? 'bg-[var(--success-color)] text-white'
                              : 'bg-[var(--card-bg)] text-[var(--text-secondary)]'
                      }`}
                    >
                      {isDone ? '✓' : index + 1}
                    </span>
                    <span className="min-w-0">
                      <span className="block font-semibold text-[var(--text-primary)]">{step.label}</span>
                      {step.description ? (
                        <span className="mt-1 block text-sm text-[var(--text-secondary)]">{step.description}</span>
                      ) : null}
                    </span>
                  </div>
                </div>
              )
            })}
          </div>

          {transactionHash ? (
            <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="text-sm font-semibold uppercase tracking-[0.08em] text-[var(--text-secondary)]">
                    Transaction Hash
                  </div>
                  <div className="mt-3 break-all text-sm font-medium text-[var(--text-primary)]">{transactionHash}</div>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    className="app-icon-button"
                    type="button"
                    onClick={() => {
                      if (transactionHash) {
                        void navigator.clipboard.writeText(transactionHash)
                      }
                    }}
                  >
                    <CopyOutlined />
                  </button>
                  {blockExplorer ? (
                    <a
                      className="app-icon-button"
                      href={`${blockExplorer}/tx/${transactionHash}`}
                      rel="noreferrer"
                      target="_blank"
                    >
                      <LinkOutlined />
                    </a>
                  ) : null}
                </div>
              </div>
            </div>
          ) : (
            <div className="rounded-2xl bg-[var(--bg-secondary)] p-5">
              <div className="space-y-4">
                {transactionDetails.map(detail => (
                  <div key={detail.label} className="flex items-start justify-between gap-4 border-b border-[var(--border-color)] pb-4 last:border-b-0 last:pb-0">
                    <span className="text-sm text-[var(--text-secondary)]">{detail.label}</span>
                    <span className="text-right">
                      {detail.values.map(value => (
                        <span
                          key={value}
                          className={`block text-sm ${
                            detail.type === 'debit'
                              ? 'text-[var(--error-color)]'
                              : detail.type === 'credit'
                                ? 'text-[var(--success-color)]'
                                : 'text-[var(--text-primary)]'
                          } ${detail.highlight ? 'font-semibold' : 'font-medium'}`}
                        >
                          {value}
                        </span>
                      ))}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {gasInfo ? (
            <div className="grid gap-3 sm:grid-cols-2">
              {[
                ['Gas Limit', gasInfo.gasLimit],
                ['Gas Price', gasInfo.gasPrice],
                ['Estimated Fee', gasInfo.estimatedFee],
                ['Max Fee', gasInfo.maxFee]
              ].map(([label, value]) => (
                <div key={label} className="rounded-2xl bg-[var(--bg-secondary)] p-4">
                  <div className="text-sm text-[var(--text-secondary)]">{label}</div>
                  <div className="mt-2 font-semibold text-[var(--text-primary)]">{value}</div>
                </div>
              ))}
            </div>
          ) : null}

          {status === 'pending' ? (
            <div className="app-inline-note is-info">Confirm the transaction in your wallet.</div>
          ) : null}

          {status === 'loading' ? (
            <div className="app-inline-note is-info">
              {steps[boundedStep]?.description || steps[boundedStep]?.label || 'Processing transaction...'}
            </div>
          ) : null}

          {status === 'error' && errorMessage ? (
            <div className="app-inline-note is-error">{errorMessage}</div>
          ) : null}

          <div className="flex flex-wrap justify-end gap-3">
            {status !== 'loading' ? (
              <button className="app-action-button is-subtle" type="button" onClick={onClose}>
                {status === 'success' ? 'Close' : 'Cancel'}
              </button>
            ) : null}
            {status === 'error' ? (
              <button className="app-action-button is-primary" type="button" onClick={onRetry}>
                Retry
              </button>
            ) : null}
            {status === 'success' && showViewTransaction && transactionHash && blockExplorer ? (
              <a
                className="app-action-button is-primary"
                href={`${blockExplorer}/tx/${transactionHash}`}
                rel="noreferrer"
                target="_blank"
              >
                View On Explorer
              </a>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}

// src/components/common/TransactionModal.vue
<template>
  <el-dialog :model-value="visible" @update:model-value="$emit('update:visible', $event)" :title="modalTitle"
    :width="dialogWidth" :close-on-click-modal="false" :close-on-press-escape="canClose" :show-close="canClose"
    @close="handleClose">
    <div class="transaction-modal">
      <!-- Transaction Steps -->
      <div class="steps-container mb-6">
        <div class="flex justify-between">
          <div v-for="(step, index) in steps" :key="index" class="step-item" :class="{
            'active': currentStep === index,
            'completed': currentStep > index,
            'pending': currentStep < index
          }">
            <div class="step-circle">
              <el-icon v-if="currentStep > index" class="text-white">
                <Check />
              </el-icon>
              <el-icon v-else-if="currentStep === index && (status === 'loading' || status === 'pending')"
                class="text-white animate-spin">
                <Loading />
              </el-icon>
              <span v-else class="text-sm font-medium">{{ index + 1 }}</span>
            </div>
            <span class="step-label">{{ step.label }}</span>
          </div>
        </div>

        <!-- Progress Line -->
        <div class="progress-line" role="progressbar" :aria-valuenow="progressPercent" aria-valuemin="0"
          aria-valuemax="100">
          <div class="progress-fill" :style="{ width: `${progressPercent}%` }"></div>
        </div>
      </div>

      <!-- Transaction Details -->
      <div v-if="transactionHash" class="transaction-details mb-6">
        <div class="detail-card">
          <h4 class="flex items-center justify-between">
            <span class="text-lg font-semibold text-gray-900 dark:text-white">{{ $t('transaction.hash') }}</span>
            <div class="flex items-center space-x-2">
              <el-button text size="small" @click="copyTransactionHash">
                <el-icon>
                  <DocumentCopy />
                </el-icon>
              </el-button>
              <el-button text size="small" @click="viewOnExplorer">
                <el-icon>
                  <Link />
                </el-icon>
              </el-button>
            </div>
          </h4>

          <div class="mt-2">
            <span class="text-xs text-gray-600 dark:text-gray-400 break-all">
              {{ transactionHash }}
            </span>
          </div>
        </div>
      </div>
      <div v-else class="transaction-details mb-6">
        <div class="detail-card">
          <h4 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            {{ $t('transaction.details') }}
          </h4>

          <div class="space-y-3">
            <div v-for="detail in transactionDetails" :key="detail.label" class="detail-row">
              <span class="detail-label">{{ detail.label }}</span>
              <div class="flex flex-col">
                <div v-for="(item, index) in detail.values" :key="index" class="detail-value" :class="[
                  detail.highlight ? 'text-primary-600 dark:text-primary-400 font-semibold' : '',
                  detail.type === 'debit' ? 'circle-bg-red' : '',
                  detail.type === 'credit' ? 'circle-bg-green' : ''
                ]">
                  {{ item }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Optional Gas Info -->
      <!-- <div v-if="gasInfo" class="mb-6">
        <div class="detail-card">
          <h4 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Gas Info</h4>
          <div class="space-y-3">
            <div class="detail-row"><span class="detail-label">Gas Limit</span><span class="detail-value">{{ gasInfo.gasLimit }}</span></div>
            <div class="detail-row"><span class="detail-label">Gas Price</span><span class="detail-value">{{ gasInfo.gasPrice }}</span></div>
            <div class="detail-row"><span class="detail-label">Estimated Fee</span><span class="detail-value">{{ gasInfo.estimatedFee }}</span></div>
            <div class="detail-row"><span class="detail-label">Max Fee</span><span class="detail-value">{{ gasInfo.maxFee }}</span></div>
          </div>
        </div>
      </div> -->

      <!-- Status Messages -->
      <div class="status-section mb-6">
        <div v-if="status === 'pending'" class="status-message info">
          <el-icon>
            <InfoFilled />
          </el-icon>
          <span>{{ $t('transaction.confirmInWallet') }}</span>
        </div>

        <div v-else-if="status === 'loading'" class="status-message loading">
          <el-icon class="animate-spin">
            <Loading />
          </el-icon>
          <span>{{ currentStepMessage }}</span>
        </div>
      </div>
    </div>

    <!-- Footer Actions -->
    <template #footer>
      <div class="flex justify-end space-x-3">
        <el-button v-if="canClose" @click="handleClose">
          {{ status === 'success' ? $t('common.close') : $t('common.cancel') }}
        </el-button>

        <el-button v-if="status === 'error'" type="primary" @click="handleRetry">
          {{ $t('common.retry') }}
        </el-button>

        <el-button v-if="status === 'success' && showViewTransaction" type="primary" @click="viewOnExplorer">
          {{ $t('transaction.viewOnExplorer') }}
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import {
  Check,
  Loading,
  InfoFilled,
  DocumentCopy,
  Link
} from '@element-plus/icons-vue'

import { useWalletStore } from '@/stores/wallet'

interface TransactionStep {
  label: string
  description?: string
}

interface TransactionDetail {
  label: string
  values: string[]
  highlight?: boolean
  type?: 'debit' | 'credit'
}

interface GasInfo {
  gasLimit: string
  gasPrice: string
  estimatedFee: string
  maxFee: string
}

interface Props {
  visible: boolean
  title?: string
  steps: TransactionStep[]
  currentStep: number
  status: 'pending' | 'loading' | 'success' | 'error'
  transactionDetails: TransactionDetail[]
  gasInfo?: GasInfo
  transactionHash?: string
  errorMessage?: string
  showViewTransaction?: boolean
}

interface Emits {
  (e: 'update:visible', value: boolean): void
  (e: 'close'): void
  (e: 'retry'): void
}

const props = withDefaults(defineProps<Props>(), {
  title: '',
  showViewTransaction: true
})

const emit = defineEmits<Emits>()

const { t } = useI18n()
const walletStore = useWalletStore()

const isMobile = ref(false)
const windowWidth = ref(window.innerWidth)

const updateWindowWidth = () => {
  windowWidth.value = window.innerWidth
  isMobile.value = windowWidth.value < 640
}

onMounted(() => {
  updateWindowWidth()
  window.addEventListener('resize', updateWindowWidth)
})

onUnmounted(() => {
  window.removeEventListener('resize', updateWindowWidth)
})

const dialogWidth = computed(() => {
  return isMobile.value ? '95%' : '500px'
})

const modalTitle = computed(() => {
  return props.title || t('transaction.title')
})

const canClose = computed(() => {
  return props.status !== 'loading'
})

const currentStepMessage = computed(() => {
  const step = props.steps[props.currentStep]
  return step?.description || step?.label || ''
})

const progressPercent = computed(() => {
  if (!props.steps?.length) return 0
  if (props.steps.length === 1) return 100
  const denom = props.steps.length - 1
  const val = (props.currentStep / denom) * 100
  return Math.max(0, Math.min(100, Math.round(val)))
})

const handleClose = () => {
  emit('update:visible', false)
  emit('close')
}

const handleRetry = () => {
  emit('retry')
}

const copyTransactionHash = async () => {
  if (!props.transactionHash) return

  try {
    await navigator.clipboard.writeText(props.transactionHash)
    ElMessage.success(t('transaction.hashCopied'))
  } catch (error) {
    console.error('Failed to copy transaction hash:', error)
    ElMessage.error(t('transaction.copyFailed'))
  }
}

const viewOnExplorer = () => {
  if (!props.transactionHash) return

  const explorerUrl = walletStore.currentNetwork?.blockExplorer
  if (explorerUrl) {
    window.open(`${explorerUrl}/tx/${props.transactionHash}`, '_blank')
  }
}

const showErrorDetails = ref(false)

const copyErrorMessage = async () => {
  if (!props.errorMessage) return
  try {
    await navigator.clipboard.writeText(props.errorMessage)
    ElMessage.success('Copied')
  } catch (e) {
    ElMessage.error('Copy failed')
  }
}

// Auto-close on success after delay
watch(
  () => props.status,
  (newStatus) => {
    if (newStatus === 'success') {
      setTimeout(() => {
        if (props.visible) {
          handleClose()
        }
      }, 3000)
    }
  }
)
</script>

<style scoped>
.transaction-modal {
  @apply max-h-[75vh] overflow-y-auto;
}

.steps-container {
  @apply relative;
}

.step-item {
  @apply flex flex-col items-center space-y-2 relative z-10;
  flex: 1;
}

.step-circle {
  @apply w-8 h-8 rounded-full flex items-center justify-center transition-all duration-300;
}

.step-item.pending .step-circle {
  @apply bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400;
}

.step-item.active .step-circle {
  background-color: var(--primary-color);
  @apply text-white;
}

.step-item.completed .step-circle {
  background-color: var(--success-color);
  @apply text-white;
}

.step-label {
  @apply text-xs text-center text-gray-600 dark:text-gray-400 max-w-20;
}

.step-item.active .step-label {
  color: var(--primary-color);
  @apply font-medium;
}

.step-item.completed .step-label {
  @apply text-green-600 dark:text-green-400;
}

.progress-line {
  @apply absolute top-4 left-0 right-0 h-0.5 bg-gray-200 dark:bg-gray-700;
}

.progress-fill {
  background-color: var(--primary-color);
  @apply h-full transition-all duration-500 ease-out;
}

.detail-card {
  background-color: var(--bg-secondary);
  @apply p-4 rounded-lg;
}

.detail-row {
  @apply flex items-center justify-between;
}

.detail-label {
  @apply text-sm text-gray-600 dark:text-gray-400;
}

.detail-value {
  @apply text-sm font-medium text-gray-900 dark:text-white text-right mb-2;
  word-break: break-word;
}

.circle-bg-green {
  @apply bg-green-100 dark:bg-green-600/30 text-green-600 dark:text-green-300 px-3 py-1 rounded-full inline-block;
  width: fit-content;
}

.circle-bg-red {
  @apply bg-red-100 dark:bg-red-600/30 text-red-600 dark:text-red-300 px-3 py-1 rounded-full inline-block;
  width: fit-content;
}

.status-message {
  @apply flex items-center space-x-3 p-3 rounded-lg;
}

.status-message.info {
  color: var(--primary-color);
  @apply bg-blue-50 dark:bg-blue-900/20;
}

.status-message.loading {
  color: var(--primary-color);
  @apply bg-primary-50 dark:bg-primary-900/20;
}

.status-message.success {
  @apply bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300;
}

.status-message.error {
  @apply bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-300;
}

.error-message-container {
  @apply overflow-x-auto;
  max-width: calc(100% - 2rem);
  scrollbar-width: thin;
}

.error-message-container::-webkit-scrollbar {
  height: 4px;
}

.error-message-container::-webkit-scrollbar-track {
  @apply bg-transparent;
}

.error-message-container::-webkit-scrollbar-thumb {
  @apply bg-gray-300 dark:bg-gray-600 rounded-full;
}

:deep(.el-dialog__body) {
  @apply pt-4;
}

:deep(.el-dialog__footer) {
  @apply pt-4 border-t border-gray-200 dark:border-gray-700;
}

@media (max-width: 640px) {
  .transaction-modal {
    @apply max-h-[70vh];
  }

  .step-circle {
    @apply w-6 h-6;
  }

  .step-label {
    @apply text-xs max-w-16;
  }

  .progress-line {
    @apply top-3;
  }

  .detail-row {
    @apply flex-col items-start space-y-1;
  }

  .detail-value {
    @apply text-left;
  }

  .status-message {
    @apply p-2;
  }

  :deep(.el-dialog__header) {
    @apply py-3 px-4;
  }

  :deep(.el-dialog__body) {
    @apply px-4 py-3;
  }

  :deep(.el-dialog__footer) {
    @apply py-3 px-4;
  }

  :deep(.el-button) {
    @apply text-sm py-1 px-2;
  }
}
</style>
